import { db } from "./index";
import {
  users,
  affiliations,
  authors,
  categories,
  roles,
  permissions,
  rolePermissions,
} from "./schema";
import { hashPassword } from "../auth/password";
import { PERMISSIONS, DEFAULT_ROLE_PERMISSIONS } from "../permission-catalog";

const CATEGORIES: { id: string; parentId: string | null; name: string; nameZh: string | null; description: string; descriptionZh: string | null }[] = [
  { id: "cs", parentId: null, name: "Computer Science", nameZh: "计算机科学", description: "All aspects of computer science, including artificial intelligence, programming languages, algorithms, and theory of computation." , descriptionZh: "计算机科学的各个方面，包括人工智能、编程语言、算法和计算理论。" },
  { id: "econ", parentId: null, name: "Economics", nameZh: "经济学", description: "Theory and applications of economics." , descriptionZh: "经济学理论与应用。" },
  { id: "eess", parentId: null, name: "Electrical Engineering and Systems Science", nameZh: "电气工程和系统科学", description: "All aspects of electrical engineering and systems science, including signal processing, systems and control, and audio and speech processing." , descriptionZh: "电气工程和系统科学的各个方面，包括信号处理、系统和控制以及音频和语音处理。" },
  { id: "math", parentId: null, name: "Mathematics", nameZh: "数学", description: "All areas of mathematics, including algebra, analysis, geometry, topology, and number theory." , descriptionZh: "数学的所有领域，包括代数、分析、几何、拓扑和数论。" },
  { id: "physics", parentId: null, name: "Physics", nameZh: "物理", description: "All aspects of physics, including astrophysics, condensed matter, and particle physics." , descriptionZh: "物理学的各个方面，包括天体物理学、凝聚态物理学和粒子物理学。" },
  { id: "q-bio", parentId: null, name: "Quantitative Biology", nameZh: "定量生物学", description: "All aspects of biology that involve quantitative approaches, including molecular biology, genomics, and systems biology." , descriptionZh: "涉及定量方法的生物学的所有方面，包括分子生物学、基因组学和系统生物学。" },
  { id: "q-fin", parentId: null, name: "Quantitative Finance", nameZh: "数量金融", description: "All aspects of quantitative finance, including mathematical finance, risk management, and portfolio management." , descriptionZh: "量化金融的各个方面，包括数学金融、风险管理和投资组合管理。" },
  { id: "stat", parentId: null, name: "Statistics", nameZh: "统计数据", description: "All aspects of statistics, including statistical theory, methodology, and applications." , descriptionZh: "统计学的各个方面，包括统计理论、方法和应用。" },
  { id: "astro-ph", parentId: null, name: "Astrophysics", nameZh: "天体物理学", description: "Phenomenology of early universe, cosmic microwave background, cosmological parameters, primordial element abundances, extragalactic distance scale, large-scale structure of the universe. Groups, superclusters, voids, intergalactic medium. Particle astrophysics: dark energy, dark matter, baryogenesis, leptogenesis, inflationary models, reheating, monopoles, WIMPs, cosmic strings, primordial black holes, cosmological gravitational radiation" , descriptionZh: "早期宇宙现象学、宇宙微波背景、宇宙学参数、原初元素丰度、河外距离尺度、宇宙大尺度结构。星团、超星系团、空隙、星系间介质。粒子天体物理学：暗能量、暗物质、重子发生、轻子发生、暴胀模型、再加热、单极子、WIMP、宇宙弦、原初黑洞、宇宙引力辐射" },
  { id: "cond-mat", parentId: null, name: "Condensed Matter", nameZh: "凝聚态物质", description: "Glasses and spin glasses; properties of random, aperiodic and quasiperiodic systems; transport in disordered media; localization; phenomena mediated by defects and disorder; neural networks" , descriptionZh: "玻璃和旋转玻璃；随机、非周期和准周期系统的性质；在无序介质中传输；本土化;由缺陷和紊乱引起的现象；神经网络" },
  { id: "gr-qc", parentId: null, name: "General Relativity and Quantum Cosmology", nameZh: "广义相对论和量子宇宙学", description: "General Relativity and Quantum Cosmology Areas of gravitational physics, including experiments and observations related to the detection and interpretation of gravitational waves, experimental tests of gravitational theories, computational general relativity, relativistic astrophysics, solutions to Einstein's equations and their properties, alternative theories of gravity, classical and quantum cosmology, and quantum gravity." , descriptionZh: "广义相对论和量子宇宙学引力物理学领域，包括与引力波的探测和解释相关的实验和观测、引力理论的实验测试、计算广义相对论、相对论天体物理学、爱因斯坦方程及其性质的解、引力的替代理论、经典和量子宇宙学以及量子引力。" },
  { id: "hep-ex", parentId: null, name: "High Energy Physics - Experiment", nameZh: "高能物理-实验", description: "Results from high-energy/particle physics experiments and prospects for future experimental results, including tests of the standard model, measurements of standard model parameters, searches for physics beyond the standard model, and astroparticle physics experimental results. Does not include: detectors and instrumentation nor analysis methods to conduct experiments." , descriptionZh: "高能/粒子物理实验的结果以及对未来实验结果的展望，包括标准模型的测试、标准模型参数的测量、标准模型之外的物理搜索以及天体粒子物理实验结果。不包括：检测器和仪器，也不包括进行实验的分析方法。" },
  { id: "hep-lat", parentId: null, name: "High Energy Physics - Lattice", nameZh: "高能物理-晶格", description: "Lattice field theory. Phenomenology from lattice field theory. Algorithms for lattice field theory. Hardware for lattice field theory." , descriptionZh: "格场理论。来自晶格场论的现象学。晶格场论的算法。格场理论的硬件。" },
  { id: "hep-ph", parentId: null, name: "High Energy Physics - Phenomenology", nameZh: "高能物理-现象学", description: "Theoretical particle physics and its interrelation with experiment. Prediction of particle physics observables: models, effective field theories, calculation techniques. Particle physics: analysis of theory through experimental results." , descriptionZh: "理论粒子物理学及其与实验的相互关系。粒子物理可观测量的预测：模型、有效场论、计算技术。粒子物理学：通过实验结果分析理论。" },
  { id: "hep-th", parentId: null, name: "High Energy Physics - Theory", nameZh: "高能物理 - 理论", description: "Formal aspects of quantum field theory. String theory, supersymmetry and supergravity." , descriptionZh: "量子场论的形式方面。弦理论、超对称性和超引力。" },
  { id: "math-ph", parentId: null, name: "Mathematical Physics", nameZh: "数学物理", description: "Articles in this category focus on areas of research that illustrate the application of mathematics to problems in physics, develop mathematical methods for such applications, or provide mathematically rigorous formulations of existing physical theories. Submissions to math-ph should be of interest to both physically oriented mathematicians and mathematically oriented physicists; submissions which are primarily of interest to theoretical physicists or to mathematicians should probably be directed to the respective physics/math categories" , descriptionZh: "此类文章侧重于说明数学在物理问题中的应用、为此类应用开发数学方法或提供现有物理理论的严格数学公式的研究领域。提交给 math-ph 的材料应该引起物理导向的数学家和数学导向的物理学家的兴趣；理论物理学家或数学家主要感兴趣的提交内容可能应该针对各自的物理/数学类别" },
  { id: "nlin", parentId: null, name: "Nonlinear Sciences", nameZh: "非线性科学", description: "Adaptation, self-organizing systems, statistical physics, fluctuating systems, stochastic processes, interacting particle systems, machine learning" , descriptionZh: "适应、自组织系统、统计物理学、涨落系统、随机过程、相互作用粒子系统、机器学习" },
  { id: "nucl-ex", parentId: null, name: "Nuclear Experiment", nameZh: "核实验", description: "Nuclear Experiment Results from experimental nuclear physics including the areas of fundamental interactions, measurements at low- and medium-energy, as well as relativistic heavy-ion collisions. Does not include: detectors and instrumentation nor analysis methods to conduct experiments; descriptions of experimental programs (present or future); comments on published results" , descriptionZh: "核实验 实验核物理的结果，包括基本相互作用领域、低能和中能测量以及相对论重离子碰撞。不包括：进行实验的探测器和仪器或分析方法；实验计划的描述（现在或未来）；对已发表结果的评论" },
  { id: "nucl-th", parentId: null, name: "Nuclear Theory", nameZh: "核理论", description: "Nuclear Theory Theory of nuclear structure covering wide area from models of hadron structure to neutron stars. Nuclear equation of states at different external conditions. Theory of nuclear reactions including heavy-ion reactions at low and high energies. It does not include problems of data analysis, physics of nuclear reactors, problems of safety, reactor construction" , descriptionZh: "核理论 核结构理论涵盖从强子结构模型到中子星的广泛领域。不同外部条件下的核状态方程。核反应理论，包括低能和高能重离子反应。它不包括数据分析、核反应堆物理、安全问题、反应堆建造问题" },
  { id: "quant-ph", parentId: null, name: "Quantum Physics", nameZh: "量子物理学", description: "Quantum mechanics, quantum information, quantum computation and quantum cryptography, quantum optics, foundations of quantum mechanics, and the quantum-classical correspondence." , descriptionZh: "量子力学、量子信息、量子计算和量子密码学、量子光学、量子力学基础以及量子经典对应。" },
  { id: "cs.AI", parentId: "cs", name: "Artificial Intelligence", nameZh: "人工智能", description: "Covers all areas of AI except Vision, Robotics, Machine Learning, Multiagent Systems, and Computation and Language (Natural Language Processing), which have separate subject areas. In particular, includes Expert Systems, Theorem Proving (although this may overlap with Logic in Computer Science), Knowledge Representation, Planning, and Uncertainty in AI. Roughly includes material in ACM Subject Classes I.2.0, I.2.1, I.2.3, I.2.4, I.2.8, and I.2.11." , descriptionZh: "涵盖人工智能的所有领域，但视觉、机器人、机器学习、多智能体系统以及计算和语言（自然语言处理）除外，这些领域有单独的学科领域。特别是，包括专家系统、定理证明（尽管这可能与计算机科学中的逻辑重叠）、知识表示、规划和人工智能中的不确定性。大致包括 ACM 主题类别 I.2.0、I.2.1、I.2.3、I.2.4、I.2.8 和 I.2.11 中的材料。" },
  { id: "cs.AR", parentId: "cs", name: "Hardware Architecture", nameZh: "硬件架构", description: "Covers systems organization and hardware architecture. Roughly includes material in ACM Subject Classes C.0, C.1, and C.5." , descriptionZh: "涵盖系统组织和硬件架构。大致包括 ACM 主题类别 C.0、C.1 和 C.5 中的材料。" },
  { id: "cs.CC", parentId: "cs", name: "Computational Complexity", nameZh: "计算复杂度", description: "Covers models of computation, complexity classes, structural complexity, complexity tradeoffs, upper and lower bounds. Roughly includes material in ACM Subject Classes F.1 (computation by abstract devices), F.2.3 (tradeoffs among complexity measures), and F.4.3 (formal languages), although some material in formal languages may be more appropriate for Logic in Computer Science. Some material in F.2.1 and F.2.2, may also be appropriate here, but is more likely to have Data Structures and Algorithms as the primary subject area." , descriptionZh: "涵盖计算模型、复杂性类别、结构复杂性、复杂性权衡、上限和下限。大致包括 ACM 主题类 F.1（抽象设备计算）、F.2.3（复杂性度量之间的权衡）和 F.4.3（形式语言）中的材料，尽管形式语言中的某些材料可能更适合计算机科学中的逻辑。 F.2.1 和 F.2.2 中的一些材料也可能适合这里，但更可能将数据结构和算法作为主要主题领域。" },
  { id: "cs.CE", parentId: "cs", name: "Computational Engineering, Finance, and Science", nameZh: "计算工程、金融和科学", description: "Covers applications of computer science to the mathematical modeling of complex systems in the fields of science, engineering, and finance. Papers here are interdisciplinary and applications-oriented, focusing on techniques and tools that enable challenging computational simulations to be performed, for which the use of supercomputers or distributed computing platforms is often required. Includes material in ACM Subject Classes J.2, J.3, and J.4 (economics)." , descriptionZh: "涵盖计算机科学在科学、工程和金融领域复杂系统数学建模中的应用。这里的论文是跨学科的和面向应用的，重点关注能够执行具有挑战性的计算模拟的技术和工具，为此通常需要使用超级计算机或分布式计算平台。包括 ACM 学科类 J.2、J.3 和 J.4（经济学）中的材料。" },
  { id: "cs.CG", parentId: "cs", name: "Computational Geometry", nameZh: "计算几何", description: "Roughly includes material in ACM Subject Classes I.3.5 and F.2.2." , descriptionZh: "大致包括 ACM 主题类别 I.3.5 和 F.2.2 中的材料。" },
  { id: "cs.CL", parentId: "cs", name: "Computation and Language", nameZh: "计算和语言", description: "Covers natural language processing. Roughly includes material in ACM Subject Class I.2.7. Note that work on artificial languages (programming languages, logics, formal systems) that does not explicitly address natural-language issues broadly construed (natural-language processing, computational linguistics, speech, text retrieval, etc.) is not appropriate for this area." , descriptionZh: "涵盖自然语言处理。大致包括 ACM 主题类别 I.2.7 中的材料。请注意，有关人工语言（编程语言、逻辑、形式系统）的工作如果没有明确解决广义上的自然语言问题（自然语言处理、计算语言学、语音、文本检索等），则不适合该领域。" },
  { id: "cs.CR", parentId: "cs", name: "Cryptography and Security", nameZh: "密码学和安全", description: "Covers all areas of cryptography and security including authentication, public key cryptosytems, proof-carrying code, etc. Roughly includes material in ACM Subject Classes D.4.6 and E.3." , descriptionZh: "涵盖密码学和安全的所有领域，包括身份验证、公钥密码系统、证明代码等。大致包括 ACM 主题类 D.4.6 和 E.3 中的材料。" },
  { id: "cs.CV", parentId: "cs", name: "Computer Vision and Pattern Recognition", nameZh: "计算机视觉和模式识别", description: "Covers image processing, computer vision, pattern recognition, and scene understanding. Roughly includes material in ACM Subject Classes I.2.10, I.4, and I.5." , descriptionZh: "涵盖图像处理、计算机视觉、模式识别和场景理解。大致包括 ACM 主题类别 I.2.10、I.4 和 I.5 中的材料。" },
  { id: "cs.CY", parentId: "cs", name: "Computers and Society", nameZh: "计算机与社会", description: "Covers impact of computers on society, computer ethics, information technology and public policy, legal aspects of computing, computers and education. Roughly includes material in ACM Subject Classes K.0, K.2, K.3, K.4, K.5, and K.7." , descriptionZh: "涵盖计算机对社会的影响、计算机伦理、信息技术和公共政策、计算机的法律方面、计算机和教育。大致包括 ACM 科目类别 K.0、K.2、K.3、K.4、K.5 和 K.7 中的材料。" },
  { id: "cs.DB", parentId: "cs", name: "Databases", nameZh: "数据库", description: "Covers database management, datamining, and data processing. Roughly includes material in ACM Subject Classes E.2, E.5, H.0, H.2, and J.1." , descriptionZh: "涵盖数据库管理、数据挖掘和数据处理。大致包括 ACM 主题类别 E.2、E.5、H.0、H.2 和 J.1 中的材料。" },
  { id: "cs.DC", parentId: "cs", name: "Distributed, Parallel, and Cluster Computing", nameZh: "分布式、并行和集群计算", description: "Covers fault-tolerance, distributed algorithms, stabilility, parallel computation, and cluster computing. Roughly includes material in ACM Subject Classes C.1.2, C.1.4, C.2.4, D.1.3, D.4.5, D.4.7, E.1." , descriptionZh: "涵盖容错、分布式算法、稳定性、并行计算和集群计算。大致包括 ACM 主题类别 C.1.2、C.1.4、C.2.4、D.1.3、D.4.5、D.4.7、E.1 中的材料。" },
  { id: "cs.DL", parentId: "cs", name: "Digital Libraries", nameZh: "数字图书馆", description: "Covers all aspects of the digital library design and document and text creation. Note that there will be some overlap with Information Retrieval (which is a separate subject area). Roughly includes material in ACM Subject Classes H.3.5, H.3.6, H.3.7, I.7." , descriptionZh: "涵盖数字图书馆设计以及文档和文本创建的各个方面。请注意，与信息检索（这是一个单独的主题领域）会有一些重叠。大致包括 ACM 主题类别 H.3.5、H.3.6、H.3.7、I.7 中的材料。" },
  { id: "cs.DM", parentId: "cs", name: "Discrete Mathematics", nameZh: "离散数学", description: "Covers combinatorics, graph theory, applications of probability. Roughly includes material in ACM Subject Classes G.2 and G.3." , descriptionZh: "涵盖组合学、图论、概率应用。大致包括 ACM 主题类别 G.2 和 G.3 中的材料。" },
  { id: "cs.DS", parentId: "cs", name: "Data Structures and Algorithms", nameZh: "数据结构和算法", description: "Covers data structures and analysis of algorithms. Roughly includes material in ACM Subject Classes E.1, E.2, F.2.1, and F.2.2." , descriptionZh: "涵盖数据结构和算法分析。大致包括 ACM 主题类别 E.1、E.2、F.2.1 和 F.2.2 中的材料。" },
  { id: "cs.ET", parentId: "cs", name: "Emerging Technologies", nameZh: "新兴技术", description: "Covers approaches to information processing (computing, communication, sensing) and bio-chemical analysis based on alternatives to silicon CMOS-based technologies, such as nanoscale electronic, photonic, spin-based, superconducting, mechanical, bio-chemical and quantum technologies (this list is not exclusive). Topics of interest include (1) building blocks for emerging technologies, their scalability and adoption in larger systems, including integration with traditional technologies, (2) modeling, design and optimization of novel devices and systems, (3) models of computation, algorithm design and programming for emerging technologies." , descriptionZh: "涵盖基于硅 CMOS 技术替代方案的信息处理（计算、通信、传感）和生物化学分析方法，例如纳米级电子、光子、自旋、超导、机械、生物化学和量子技术（此列表并非唯一）。感兴趣的主题包括（1）新兴技术的构建模块、其可扩展性和在更大系统中的采用，包括与传统技术的集成，（2）新型设备和系统的建模、设计和优化，（3）新兴技术的计算模型、算法设计和编程。" },
  { id: "cs.FL", parentId: "cs", name: "Formal Languages and Automata Theory", nameZh: "形式语言和自动机理论", description: "Covers automata theory, formal language theory, grammars, and combinatorics on words. This roughly corresponds to ACM Subject Classes F.1.1, and F.4.3. Papers dealing with computational complexity should go to cs.CC; papers dealing with logic should go to cs.LO." , descriptionZh: "涵盖自动机理论、形式语言理论、语法和单词组合学。这大致对应于 ACM 主题类别 F.1.1 和 F.4.3。处理计算复杂性的论文应该去cs.CC；涉及逻辑的论文应该去cs.LO。" },
  { id: "cs.GL", parentId: "cs", name: "General Literature", nameZh: "一般文学", description: "Covers introductory material, survey material, predictions of future trends, biographies, and miscellaneous computer-science related material. Roughly includes all of ACM Subject Class A, except it does not include conference proceedings (which will be listed in the appropriate subject area)." , descriptionZh: "涵盖介绍性材料、调查材料、未来趋势预测、传记以及各种计算机科学相关材料。大致包括 ACM A 类主题的所有内容，但不包括会议记录（将在相应的主题区域中列出）。" },
  { id: "cs.GR", parentId: "cs", name: "Graphics", nameZh: "图形", description: "Covers all aspects of computer graphics. Roughly includes material in all of ACM Subject Class I.3, except that I.3.5 is is likely to have Computational Geometry as the primary subject area." , descriptionZh: "涵盖计算机图形学的各个方面。大致包括 ACM 学科 I.3 类的所有材料，但 I.3.5 可能将计算几何作为主要学科领域。" },
  { id: "cs.GT", parentId: "cs", name: "Computer Science and Game Theory", nameZh: "计算机科学与博弈论", description: "Covers all theoretical and applied aspects at the intersection of computer science and game theory, including work in mechanism design, learning in games (which may overlap with Learning), foundations of agent modeling in games (which may overlap with Multiagent systems), coordination, specification and formal methods for non-cooperative computational environments. The area also deals with applications of game theory to areas such as electronic commerce." , descriptionZh: "涵盖计算机科学和博弈论交叉点的所有理论和应用方面，包括机制设计、游戏中的学习（可能与学习重叠）、游戏中代理建模的基础（可能与多代理系统重叠）、非合作计算环境的协调、规范和形式化方法。该领域还涉及博弈论在电子商务等领域的应用。" },
  { id: "cs.HC", parentId: "cs", name: "Human-Computer Interaction", nameZh: "人机交互", description: "Covers human factors, user interfaces, and collaborative computing. Roughly includes material in ACM Subject Classes H.1.2 and all of H.5, except for H.5.1, which is more likely to have Multimedia as the primary subject area." , descriptionZh: "涵盖人为因素、用户界面和协作计算。大致包括 ACM 主题类 H.1.2 和所有 H.5 中的材料，H.5.1 除外，后者更可能将多媒体作为主要主题领域。" },
  { id: "cs.IR", parentId: "cs", name: "Information Retrieval", nameZh: "信息检索", description: "Covers indexing, dictionaries, retrieval, content and analysis. Roughly includes material in ACM Subject Classes H.3.0, H.3.1, H.3.2, H.3.3, and H.3.4." , descriptionZh: "涵盖索引、词典、检索、内容和分析。大致包括 ACM 主题类别 H.3.0、H.3.1、H.3.2、H.3.3 和 H.3.4 中的材料。" },
  { id: "cs.IT", parentId: "cs", name: "Information Theory", nameZh: "信息论", description: "Covers theoretical and experimental aspects of information theory and coding. Includes material in ACM Subject Class E.4 and intersects with H.1.1." , descriptionZh: "涵盖信息论和编码的理论和实验方面。包括 ACM 主题类别 E.4 中的材料并与 H.1.1 交叉。" },
  { id: "cs.LG", parentId: "cs", name: "Machine Learning", nameZh: "机器学习", description: "Papers on all aspects of machine learning research (supervised, unsupervised, reinforcement learning, bandit problems, and so on) including also robustness, explanation, fairness, and methodology. cs.LG is also an appropriate primary category for applications of machine learning methods." , descriptionZh: "关于机器学习研究各个方面（监督、无监督、强化学习、强盗问题等）的论文，包括鲁棒性、解释、公平性和方法论。 cs.LG 也是机器学习方法应用的合适主要类别。" },
  { id: "cs.LO", parentId: "cs", name: "Logic in Computer Science", nameZh: "计算机科学中的逻辑", description: "Covers all aspects of logic in computer science, including finite model theory, logics of programs, modal logic, and program verification. Programming language semantics should have Programming Languages as the primary subject area. Roughly includes material in ACM Subject Classes D.2.4, F.3.1, F.4.0, F.4.1, and F.4.2; some material in F.4.3 (formal languages) may also be appropriate here, although Computational Complexity is typically the more appropriate subject area." , descriptionZh: "涵盖计算机科学中逻辑的各个方面，包括有限模型理论、程序逻辑、模态逻辑和程序验证。编程语言语义应将编程语言作为主要主题领域。大致包括 ACM 主题类别 D.2.4、F.3.1、F.4.0、F.4.1 和 F.4.2 中的材料； F.4.3（形式语言）中的一些材料也可能适合这里，尽管计算复杂性通常是更合适的主题领域。" },
  { id: "cs.MA", parentId: "cs", name: "Multiagent Systems", nameZh: "多代理系统", description: "Covers multiagent systems, distributed artificial intelligence, intelligent agents, coordinated interactions. and practical applications. Roughly covers ACM Subject Class I.2.11." , descriptionZh: "涵盖多智能体系统、分布式人工智能、智能代理、协调交互。和实际应用。大致涵盖 ACM 主题类别 I.2.11。" },
  { id: "cs.MM", parentId: "cs", name: "Multimedia", nameZh: "多媒体", description: "Roughly includes material in ACM Subject Class H.5.1." , descriptionZh: "大致包括 ACM 主题类别 H.5.1 中的材料。" },
  { id: "cs.MS", parentId: "cs", name: "Mathematical Software", nameZh: "数学软件", description: "Roughly includes material in ACM Subject Class G.4." , descriptionZh: "大致包括 ACM 主题类别 G.4 中的材料。" },
  { id: "cs.NA", parentId: "cs", name: "Numerical Analysis", nameZh: "数值分析", description: "cs.NA is an alias for math.NA. Roughly includes material in ACM Subject Class G.1." , descriptionZh: "cs.NA 是 math.NA 的别名。大致包括 ACM 主题类别 G.1 中的材料。" },
  { id: "cs.NE", parentId: "cs", name: "Neural and Evolutionary Computing", nameZh: "神经和进化计算", description: "Covers neural networks, connectionism, genetic algorithms, artificial life, adaptive behavior. Roughly includes some material in ACM Subject Class C.1.3, I.2.6, I.5." , descriptionZh: "涵盖神经网络、联结主义、遗传算法、人工生命、自适应行为。大致包括 ACM 主题类别 C.1.3、I.2.6、I.5 中的一些材料。" },
  { id: "cs.NI", parentId: "cs", name: "Networking and Internet Architecture", nameZh: "网络和互联网架构", description: "Covers all aspects of computer communication networks, including network architecture and design, network protocols, and internetwork standards (like TCP/IP). Also includes topics, such as web caching, that are directly relevant to Internet architecture and performance. Roughly includes all of ACM Subject Class C.2 except C.2.4, which is more likely to have Distributed, Parallel, and Cluster Computing as the primary subject area." , descriptionZh: "涵盖计算机通信网络的各个方面，包括网络体系结构和设计、网络协议和互联标准（如 TCP/IP）。还包括与 Internet 体系结构和性能直接相关的主题，例如 Web 缓存。大致包括除 C.2.4 之外的所有 ACM 主题类别 C.2，后者更可能将分布式、并行和集群计算作为主要主题领域。" },
  { id: "cs.OH", parentId: "cs", name: "Other Computer Science", nameZh: "其他计算机科学", description: "This is the classification to use for documents that do not fit anywhere else." , descriptionZh: "这是用于不适合其他任何地方的文档的分类。" },
  { id: "cs.OS", parentId: "cs", name: "Operating Systems", nameZh: "操作系统", description: "Roughly includes material in ACM Subject Classes D.4.1, D.4.2., D.4.3, D.4.4, D.4.5, D.4.7, and D.4.9." , descriptionZh: "大致包括 ACM 主题类别 D.4.1、D.4.2.、D.4.3、D.4.4、D.4.5、D.4.7 和 D.4.9 中的材料。" },
  { id: "cs.PF", parentId: "cs", name: "Performance", nameZh: "表现", description: "Covers performance measurement and evaluation, queueing, and simulation. Roughly includes material in ACM Subject Classes D.4.8 and K.6.2." , descriptionZh: "涵盖性能测量和评估、排队和模拟。大致包括 ACM 主题类别 D.4.8 和 K.6.2 中的材料。" },
  { id: "cs.PL", parentId: "cs", name: "Programming Languages", nameZh: "编程语言", description: "Covers programming language semantics, language features, programming approaches (such as object-oriented programming, functional programming, logic programming). Also includes material on compilers oriented towards programming languages; other material on compilers may be more appropriate in Architecture (AR). Roughly includes material in ACM Subject Classes D.1 and D.3." , descriptionZh: "涵盖编程语言语义、语言特性、编程方法（如面向对象编程、函数式编程、逻辑编程）。还包括面向编程语言的编译器的材料；有关编译器的其他材料可能更适合架构 (AR)。大致包括 ACM 主题类别 D.1 和 D.3 中的材料。" },
  { id: "cs.RO", parentId: "cs", name: "Robotics", nameZh: "机器人技术", description: "Roughly includes material in ACM Subject Class I.2.9." , descriptionZh: "大致包括 ACM 主题类别 I.2.9 中的材料。" },
  { id: "cs.SC", parentId: "cs", name: "Symbolic Computation", nameZh: "符号计算", description: "Roughly includes material in ACM Subject Class I.1." , descriptionZh: "大致包括 ACM 主题 I.1 类中的材料。" },
  { id: "cs.SD", parentId: "cs", name: "Sound", nameZh: "声音", description: "Covers all aspects of computing with sound, and sound as an information channel. Includes models of sound, analysis and synthesis, audio user interfaces, sonification of data, computer music, and sound signal processing. Includes ACM Subject Class H.5.5, and intersects with H.1.2, H.5.1, H.5.2, I.2.7, I.5.4, I.6.3, J.5, K.4.2." , descriptionZh: "涵盖了声音计算以及声音作为信息通道的各个方面。包括声音模型、分析和合成、音频用户界面、数据声音化、计算机音乐和声音信号处理。包括 ACM 主题类别 H.5.5，并与 H.1.2、H.5.1、H.5.2、I.2.7、I.5.4、I.6.3、J.5、K.4.2 交叉。" },
  { id: "cs.SE", parentId: "cs", name: "Software Engineering", nameZh: "软件工程", description: "Covers design tools, software metrics, testing and debugging, programming environments, etc. Roughly includes material in all of ACM Subject Classes D.2, except that D.2.4 (program verification) should probably have Logics in Computer Science as the primary subject area." , descriptionZh: "涵盖设计工具、软件指标、测试和调试、编程环境等。大致包括所有 ACM 主题类 D.2 中的材料，但 D.2.4（程序验证）可能应将计算机科学中的逻辑作为主要主题领域。" },
  { id: "cs.SI", parentId: "cs", name: "Social and Information Networks", nameZh: "社交和信息网络", description: "Covers the design, analysis, and modeling of social and information networks, including their applications for on-line information access, communication, and interaction, and their roles as datasets in the exploration of questions in these and other domains, including connections to the social and biological sciences. Analysis and modeling of such networks includes topics in ACM Subject classes F.2, G.2, G.3, H.2, and I.2; applications in computing include topics in H.3, H.4, and H.5; and applications at the interface of computing and other disciplines include topics in J.1--J.7. Papers on computer communication systems and network protocols (e.g. TCP/IP) are generally a closer fit to the Networking and Internet Architecture (cs.NI) category." , descriptionZh: "涵盖社交和信息网络的设计、分析和建模，包括它们在在线信息访问、通信和交互方面的应用，以及它们作为数据集在探索这些领域和其他领域问题中的作用，包括与社会科学和生物科学的联系。此类网络的分析和建模包括 ACM 主题类别 F.2、G.2、G.3、H.2 和 I.2 中的主题；计算中的应用包括 H.3、H.4 和 H.5 中的主题；计算与其他学科接口的应用包括 J.1--J.7 中的主题。关于计算机通信系统和网络协议（例如 TCP/IP）的论文通常更适合网络和互联网架构（cs.NI）类别。" },
  { id: "cs.SY", parentId: "cs", name: "Systems and Control", nameZh: "系统与控制", description: "cs.SY is an alias for eess.SY. This section includes theoretical and experimental research covering all facets of automatic control systems. The section is focused on methods of control system analysis and design using tools of modeling, simulation and optimization. Specific areas of research include nonlinear, distributed, adaptive, stochastic and robust control in addition to hybrid and discrete event systems. Application areas include automotive and aerospace control systems, network control, biological systems, multiagent and cooperative control, robotics, reinforcement learning, sensor networks, control of cyber-physical and energy-related systems, and control of computing systems." , descriptionZh: "cs.SY 是 eess.SY 的别名。本节包括涵盖自动控制系统各个方面的理论和实验研究。本节重点介绍使用建模、仿真和优化工具进行控制系统分析和设计的方法。除了混合和离散事件系统之外，具体的研究领域还包括非线性、分布式、自适应、随机和鲁棒控制。应用领域包括汽车和航空航天控制系统、网络控制、生物系统、多智能体和协作控制、机器人、强化学习、传感器网络、网络物理和能源相关系统的控制以及计算系统的控制。" },
  { id: "econ.EM", parentId: "econ", name: "Econometrics", nameZh: "计量经济学", description: "Econometric Theory, Micro-Econometrics, Macro-Econometrics, Empirical Content of Economic Relations discovered via New Methods, Methodological Aspects of the Application of Statistical Inference to Economic Data." , descriptionZh: "计量经济学理论、微观计量经济学、宏观计量经济学、通过新方法发现的经济关系的实证内容、统计推断在经济数据中的应用的方法论方面。" },
  { id: "econ.GN", parentId: "econ", name: "General Economics", nameZh: "普通经济学", description: "General methodological, applied, and empirical contributions to economics." , descriptionZh: "对经济学的一般方法论、应用和实证贡献。" },
  { id: "econ.TH", parentId: "econ", name: "Theoretical Economics", nameZh: "理论经济学", description: "Includes theoretical contributions to Contract Theory, Decision Theory, Game Theory, General Equilibrium, Growth, Learning and Evolution, Macroeconomics, Market and Mechanism Design, and Social Choice." , descriptionZh: "包括对契约论、决策论、博弈论、一般均衡、增长、学习和进化、宏观经济学、市场和机制设计以及社会选择的理论贡献。" },
  { id: "eess.AS", parentId: "eess", name: "Audio and Speech Processing", nameZh: "音频和语音处理", description: "Theory and methods for processing signals representing audio, speech, and language, and their applications. This includes analysis, synthesis, enhancement, transformation, classification and interpretation of such signals as well as the design, development, and evaluation of associated signal processing systems. Machine learning and pattern analysis applied to any of the above areas is also welcome. Specific topics of interest include: auditory modeling and hearing aids; acoustic beamforming and source localization; classification of acoustic scenes; speaker separation; active noise control and echo cancellation; enhancement; de-reverberation; bioacoustics; music signals analysis, synthesis and modification; music information retrieval; audio for multimedia and joint audio-video processing; spoken and written language modeling, segmentation, tagging, parsing, understanding, and translation; text mining; speech production, perception, and psychoacoustics; speech analysis, synthesis, and perceptual modeling and coding; robust speech recognition; speaker recognition and characterization; deep learning, online learning, and graphical models applied to speech, audio, and language signals; and implementation aspects ranging from system architecture to fast algorithms." , descriptionZh: "处理表示音频、语音和语言的信号的理论和方法及其应用。这包括此类信号的分析、合成、增强、转换、分类和解释，以及相关信号处理系统的设计、开发和评估。应用于上述任何领域的机器学习和模式分析也受到欢迎。感兴趣的具体主题包括：听觉建模和助听器；声波束形成和声源定位；声学场景的分类；扬声器分离；主动噪声控制和回声消除；增强；去混响；生物声学；音乐信号分析、合成和修改；音乐信息检索；用于多媒体和联合音视频处理的音频；口语和书面语言建模、分段、标记、解析、理解和翻译；文本挖掘；言语产生、感知和心理声学；语音分析、合成、感知建模和编码；强大的语音识别能力；说话人识别和表征；应用于语音、音频和语言信号的深度学习、在线学习和图形模型；以及从系统架构到快速算法的实现方面。" },
  { id: "eess.IV", parentId: "eess", name: "Image and Video Processing", nameZh: "图像和视频处理", description: "Theory, algorithms, and architectures for the formation, capture, processing, communication, analysis, and display of images, video, and multidimensional signals in a wide variety of applications. Topics of interest include: mathematical, statistical, and perceptual image and video modeling and representation; linear and nonlinear filtering, de-blurring, enhancement, restoration, and reconstruction from degraded, low-resolution or tomographic data; lossless and lossy compression and coding; segmentation, alignment, and recognition; image rendering, visualization, and printing; computational imaging, including ultrasound, tomographic and magnetic resonance imaging; and image and video analysis, synthesis, storage, search and retrieval." , descriptionZh: "用于在各种应用中形成、捕获、处理、通信、分析和显示图像、视频和多维信号的理论、算法和架构。感兴趣的主题包括：数学、统计和感知图像和视频建模和表示；对退化、低分辨率或断层扫描数据进行线性和非线性滤波、去模糊、增强、恢复和重建；无损和有损压缩和编码；分割、对齐和识别；图像渲染、可视化和打印；计算成像，包括超声、断层扫描和磁共振成像；以及图像和视频分析、合成、存储、搜索和检索。" },
  { id: "eess.SP", parentId: "eess", name: "Signal Processing", nameZh: "信号处理", description: "Theory, algorithms, performance analysis and applications of signal and data analysis, including physical modeling, processing, detection and parameter estimation, learning, mining, retrieval, and information extraction. The term &#34;signal&#34; includes speech, audio, sonar, radar, geophysical, physiological, (bio-) medical, image, video, and multimodal natural and man-made signals, including communication signals and data. Topics of interest include: statistical signal processing, spectral estimation and system identification; filter design, adaptive filtering / stochastic learning; (compressive) sampling, sensing, and transform-domain methods including fast algorithms; signal processing for machine learning and machine learning for signal processing applications; in-network and graph signal processing; convex and nonconvex optimization methods for signal processing applications; radar, sonar, and sensor array beamforming and direction finding; communications signal processing; low power, multi-core and system-on-chip signal processing; sensing, communication, analysis and optimization for cyber-physical systems such as power grids and the Internet of Things." , descriptionZh: "信号和数据分析的理论、算法、性能分析和应用，包括物理建模、处理、检测和参数估计、学习、挖掘、检索和信息提取。术语“信号”包括语音、音频、声纳、雷达、地球物理、生理、(生物)医学、图像、视频以及多模态自然和人造信号，包括通信信号和数据。感兴趣的主题包括：统计信号处理、频谱估计和系统识别；滤波器设计、自适应滤波/随机学习； （压缩）采样、传感和变换域方法，包括快速算法；用于机器学习的信号处理和用于信号处理应用的机器学习；网内和图形信号处理；用于信号处理应用的凸和非凸优化方法；雷达、声纳和传感器阵列波束形成和测向；通信信号处理；低功耗、多核和片上系统信号处理；电网和物联网等信息物理系统的传感、通信、分析和优化。" },
  { id: "eess.SY", parentId: "eess", name: "Systems and Control", nameZh: "系统与控制", description: "This section includes theoretical and experimental research covering all facets of automatic control systems. The section is focused on methods of control system analysis and design using tools of modeling, simulation and optimization. Specific areas of research include nonlinear, distributed, adaptive, stochastic and robust control in addition to hybrid and discrete event systems. Application areas include automotive and aerospace control systems, network control, biological systems, multiagent and cooperative control, robotics, reinforcement learning, sensor networks, control of cyber-physical and energy-related systems, and control of computing systems." , descriptionZh: "本节包括涵盖自动控制系统各个方面的理论和实验研究。本节重点介绍使用建模、仿真和优化工具进行控制系统分析和设计的方法。除了混合和离散事件系统之外，具体的研究领域还包括非线性、分布式、自适应、随机和鲁棒控制。应用领域包括汽车和航空航天控制系统、网络控制、生物系统、多智能体和协作控制、机器人、强化学习、传感器网络、网络物理和能源相关系统的控制以及计算系统的控制。" },
  { id: "math.AC", parentId: "math", name: "Commutative Algebra", nameZh: "交换代数", description: "Commutative rings, modules, ideals, homological algebra, computational aspects, invariant theory, connections to algebraic geometry and combinatorics" , descriptionZh: "交换环、模、理想、同调代数、计算方面、不变理论、与代数几何和组合学的联系" },
  { id: "math.AG", parentId: "math", name: "Algebraic Geometry", nameZh: "代数几何", description: "Algebraic varieties, stacks, sheaves, schemes, moduli spaces, complex geometry, quantum cohomology" , descriptionZh: "代数簇、栈、滑轮、方案、模空间、复几何、量子上同调" },
  { id: "math.AP", parentId: "math", name: "Analysis of PDEs", nameZh: "偏微分方程分析", description: "Existence and uniqueness, boundary conditions, linear and non-linear operators, stability, soliton theory, integrable PDE's, conservation laws, qualitative dynamics" , descriptionZh: "存在性和唯一性、边界条件、线性和非线性算子、稳定性、孤子理论、可积偏微分方程、守恒定律、定性动力学" },
  { id: "math.AT", parentId: "math", name: "Algebraic Topology", nameZh: "代数拓扑", description: "Homotopy theory, homological algebra, algebraic treatments of manifolds" , descriptionZh: "同伦论、同调代​​数、流形的代数处理" },
  { id: "math.CA", parentId: "math", name: "Classical Analysis and ODEs", nameZh: "经典分析和常微分方程", description: "Special functions, orthogonal polynomials, harmonic analysis, ODE's, differential relations, calculus of variations, approximations, expansions, asymptotics" , descriptionZh: "特殊函数、正交多项式、调和分析、常微分方程、微分关系、变分法、近似、展开、渐近" },
  { id: "math.CO", parentId: "math", name: "Combinatorics", nameZh: "组合学", description: "Discrete mathematics, graph theory, enumeration, combinatorial optimization, Ramsey theory, combinatorial game theory" , descriptionZh: "离散数学、图论、枚举、组合优化、拉姆齐理论、组合博弈论" },
  { id: "math.CT", parentId: "math", name: "Category Theory", nameZh: "范畴论", description: "Enriched categories, topoi, abelian categories, monoidal categories, homological algebra" , descriptionZh: "丰富范畴、topoi、阿贝尔范畴、幺半群范畴、同调代数" },
  { id: "math.CV", parentId: "math", name: "Complex Variables", nameZh: "复杂变量", description: "Holomorphic functions, automorphic group actions and forms, pseudoconvexity, complex geometry, analytic spaces, analytic sheaves" , descriptionZh: "全纯函数、自守群作用和形式、伪凸性、复几何、解析空间、解析滑轮" },
  { id: "math.DG", parentId: "math", name: "Differential Geometry", nameZh: "微分几何", description: "Complex, contact, Riemannian, pseudo-Riemannian and Finsler geometry, relativity, gauge theory, global analysis" , descriptionZh: "复数、接触、黎曼、伪黎曼和芬斯勒几何、相对论、规范论、全局分析" },
  { id: "math.DS", parentId: "math", name: "Dynamical Systems", nameZh: "动力系统", description: "Dynamics of differential equations and flows, mechanics, classical few-body problems, iterations, complex dynamics, delayed differential equations" , descriptionZh: "微分方程和流动动力学、力学、经典少体问题、迭代、复杂动力学、延迟微分方程" },
  { id: "math.FA", parentId: "math", name: "Functional Analysis", nameZh: "泛函分析", description: "Banach spaces, function spaces, real functions, integral transforms, theory of distributions, measure theory" , descriptionZh: "Banach 空间、函数空间、实函数、积分变换、分布理论、测度论" },
  { id: "math.GM", parentId: "math", name: "General Mathematics", nameZh: "普通数学", description: "Mathematical material of general interest, topics not covered elsewhere" , descriptionZh: "普遍感兴趣的数学材料，其他地方未涵盖的主题" },
  { id: "math.GN", parentId: "math", name: "General Topology", nameZh: "通用拓扑", description: "Continuum theory, point-set topology, spaces with algebraic structure, foundations, dimension theory, local and global properties" , descriptionZh: "连续统理论、点集拓扑、代数结构空间、基础、维数论、局部和全局属性" },
  { id: "math.GR", parentId: "math", name: "Group Theory", nameZh: "群论", description: "Finite groups, topological groups, representation theory, cohomology, classification and structure" , descriptionZh: "有限群、拓扑群、表示论、上同调、分类和结构" },
  { id: "math.GT", parentId: "math", name: "Geometric Topology", nameZh: "几何拓扑", description: "Manifolds, orbifolds, polyhedra, cell complexes, foliations, geometric structures" , descriptionZh: "流形、轨道、多面体、细胞复合体、叶状结构、几何结构" },
  { id: "math.HO", parentId: "math", name: "History and Overview", nameZh: "历史与概述", description: "Biographies, philosophy of mathematics, mathematics education, recreational mathematics, communication of mathematics, ethics in mathematics" , descriptionZh: "传记、数学哲学、数学教育、娱乐数学、数学传播、数学伦理" },
  { id: "math.IT", parentId: "math", name: "Information Theory", nameZh: "信息论", description: "math.IT is an alias for cs.IT. Covers theoretical and experimental aspects of information theory and coding." , descriptionZh: "math.IT 是 cs.IT 的别名。涵盖信息论和编码的理论和实验方面。" },
  { id: "math.KT", parentId: "math", name: "K-Theory and Homology", nameZh: "K-理论和同源性", description: "Algebraic and topological K-theory, relations with topology, commutative algebra, and operator algebras" , descriptionZh: "代数和拓扑 K 理论、与拓扑的关系、交换代数和算子代数" },
  { id: "math.LO", parentId: "math", name: "Logic", nameZh: "逻辑", description: "Logic, set theory, point-set topology, formal mathematics" , descriptionZh: "逻辑、集合论、点集拓扑、形式数学" },
  { id: "math.MG", parentId: "math", name: "Metric Geometry", nameZh: "公制几何", description: "Euclidean, hyperbolic, discrete, convex, coarse geometry, comparisons in Riemannian geometry, symmetric spaces" , descriptionZh: "欧几里得、双曲、离散、凸、粗几何、黎曼几何比较、对称空间" },
  { id: "math.MP", parentId: "math", name: "Mathematical Physics", nameZh: "数学物理", description: "math.MP is an alias for math-ph. Articles in this category focus on areas of research that illustrate the application of mathematics to problems in physics, develop mathematical methods for such applications, or provide mathematically rigorous formulations of existing physical theories. Submissions to math-ph should be of interest to both physically oriented mathematicians and mathematically oriented physicists; submissions which are primarily of interest to theoretical physicists or to mathematicians should probably be directed to the respective physics/math categories" , descriptionZh: "math.MP 是 math-ph 的别名。此类文章侧重于说明数学在物理问题中的应用、为此类应用开发数学方法或提供现有物理理论的严格数学公式的研究领域。提交给 math-ph 的材料应该引起物理导向的数学家和数学导向的物理学家的兴趣；理论物理学家或数学家主要感兴趣的提交内容可能应该针对各自的物理/数学类别" },
  { id: "math.NA", parentId: "math", name: "Numerical Analysis", nameZh: "数值分析", description: "Numerical algorithms for problems in analysis and algebra, scientific computation" , descriptionZh: "分析和代数、科学计算中问题的数值算法" },
  { id: "math.NT", parentId: "math", name: "Number Theory", nameZh: "数论", description: "Prime numbers, diophantine equations, analytic number theory, algebraic number theory, arithmetic geometry, Galois theory" , descriptionZh: "素数、丢番图方程、解析数论、代数数论、算术几何、伽罗瓦理论" },
  { id: "math.OA", parentId: "math", name: "Operator Algebras", nameZh: "算子代数", description: "Algebras of operators on Hilbert space, C^*-algebras, von Neumann algebras, non-commutative geometry" , descriptionZh: "希尔伯特空间上的算子代数、C^*-代数、冯诺依曼代数、非交换几何" },
  { id: "math.OC", parentId: "math", name: "Optimization and Control", nameZh: "优化与控制", description: "Operations research, linear programming, control theory, systems theory, optimal control, game theory" , descriptionZh: "运筹学、线性规划、控制论、系统论、最优控制、博弈论" },
  { id: "math.PR", parentId: "math", name: "Probability", nameZh: "可能性", description: "Theory and applications of probability and stochastic processes: e.g. central limit theorems, large deviations, stochastic differential equations, models from statistical mechanics, queuing theory" , descriptionZh: "概率和随机过程的理论和应用：例如中心极限定理、大偏差、随机微分方程、统计力学模型、排队论" },
  { id: "math.QA", parentId: "math", name: "Quantum Algebra", nameZh: "量子代数", description: "Quantum groups, skein theories, operadic and diagrammatic algebra, quantum field theory" , descriptionZh: "量子群、绞纱理论、歌剧代数和图解代数、量子场论" },
  { id: "math.RA", parentId: "math", name: "Rings and Algebras", nameZh: "环和代数", description: "Non-commutative rings and algebras, non-associative algebras, universal algebra and lattice theory, linear algebra, semigroups" , descriptionZh: "非交换环和代数、非结合代数、普代数和格论、线性代数、半群" },
  { id: "math.RT", parentId: "math", name: "Representation Theory", nameZh: "表征论", description: "Linear representations of algebras and groups, Lie theory, associative algebras, multilinear algebra" , descriptionZh: "代数和群的线性表示、李理论、关联代数、多重线性代数" },
  { id: "math.SG", parentId: "math", name: "Symplectic Geometry", nameZh: "辛几何", description: "Hamiltonian systems, symplectic flows, classical integrable systems" , descriptionZh: "哈密​​顿系统、辛流、经典可积系统" },
  { id: "math.SP", parentId: "math", name: "Spectral Theory", nameZh: "谱理论", description: "Schrodinger operators, operators on manifolds, general differential operators, numerical studies, integral operators, discrete models, resonances, non-self-adjoint operators, random operators/matrices" , descriptionZh: "薛定谔算子、流形算子、一般微分算子、数值研究、积分算子、离散模型、共振、非自伴算子、随机算子/矩阵" },
  { id: "math.ST", parentId: "math", name: "Statistics Theory", nameZh: "统计理论", description: "Applied, computational and theoretical statistics: e.g. statistical inference, regression, time series, multivariate analysis, data analysis, Markov chain Monte Carlo, design of experiments, case studies" , descriptionZh: "应用统计、计算统计和理论统计：例如统计推断、回归、时间序列、多元分析、数据分析、马尔可夫链蒙特卡罗、实验设计、案例研究" },
  { id: "astro-ph.CO", parentId: "astro-ph", name: "Cosmology and Nongalactic Astrophysics", nameZh: "宇宙学和非银河系天体物理学", description: "Phenomenology of early universe, cosmic microwave background, cosmological parameters, primordial element abundances, extragalactic distance scale, large-scale structure of the universe. Groups, superclusters, voids, intergalactic medium. Particle astrophysics: dark energy, dark matter, baryogenesis, leptogenesis, inflationary models, reheating, monopoles, WIMPs, cosmic strings, primordial black holes, cosmological gravitational radiation" , descriptionZh: "早期宇宙现象学、宇宙微波背景、宇宙学参数、原初元素丰度、河外距离尺度、宇宙大尺度结构。星团、超星系团、空隙、星系间介质。粒子天体物理学：暗能量、暗物质、重子发生、轻子发生、暴胀模型、再加热、单极子、WIMP、宇宙弦、原初黑洞、宇宙引力辐射" },
  { id: "astro-ph.EP", parentId: "astro-ph", name: "Earth and Planetary Astrophysics", nameZh: "地球和行星天体物理学", description: "Interplanetary medium, planetary physics, planetary astrobiology, extrasolar planets, comets, asteroids, meteorites. Structure and formation of the solar system" , descriptionZh: "行星际介质、行星物理学、行星天体生物学、太阳系外行星、彗星、小行星、陨石。太阳系的结构和形成" },
  { id: "astro-ph.GA", parentId: "astro-ph", name: "Astrophysics of Galaxies", nameZh: "星系天体物理学", description: "Phenomena pertaining to galaxies or the Milky Way. Star clusters, HII regions and planetary nebulae, the interstellar medium, atomic and molecular clouds, dust. Stellar populations. Galactic structure, formation, dynamics. Galactic nuclei, bulges, disks, halo. Active Galactic Nuclei, supermassive black holes, quasars. Gravitational lens systems. The Milky Way and its contents" , descriptionZh: "与星系或银河系有关的现象。星团、HII 区域和行星状星云、星际介质、原子和分子云、尘埃。恒星种群。银河结构、形成、动力学。星系核、核球、盘、晕。活动星系核、超大质量黑洞、类星体。引力透镜系统。银河系及其内容物" },
  { id: "astro-ph.HE", parentId: "astro-ph", name: "High Energy Astrophysical Phenomena", nameZh: "高能天体物理现象", description: "Cosmic ray production, acceleration, propagation, detection. Gamma ray astronomy and bursts, X-rays, charged particles, supernovae and other explosive phenomena, stellar remnants and accretion systems, jets, microquasars, neutron stars, pulsars, black holes" , descriptionZh: "宇宙射线的产生、加速、传播、探测。伽马射线天文学和爆发、X射线、带电粒子、超新星和其他爆炸现象、恒星遗迹和吸积系统、喷流、微类星体、中子星、脉冲星、黑洞" },
  { id: "astro-ph.IM", parentId: "astro-ph", name: "Instrumentation and Methods for Astrophysics", nameZh: "天体物理学仪器和方法", description: "Detector and telescope design, experiment proposals. Laboratory Astrophysics. Methods for data analysis, statistical methods. Software, database design" , descriptionZh: "探测器和望远镜设计、实验建议。实验室天体物理学。数据分析方法、统计方法。软件、数据库设计" },
  { id: "astro-ph.SR", parentId: "astro-ph", name: "Solar and Stellar Astrophysics", nameZh: "太阳和恒星天体物理学", description: "White dwarfs, brown dwarfs, cataclysmic variables. Star formation and protostellar systems, stellar astrobiology, binary and multiple systems of stars, stellar evolution and structure, coronas. Central stars of planetary nebulae. Helioseismology, solar neutrinos, production and detection of gravitational radiation from stellar systems" , descriptionZh: "白矮星、褐矮星、灾难变星。恒星形成和原恒星系统、恒星天体生物学、恒星双星和多重系统、恒星演化和结构、日冕。行星状星云的中心恒星。日震学、太阳中微子、恒星系统引力辐射的产生和检测" },
  { id: "cond-mat.dis-nn", parentId: "cond-mat", name: "Disordered Systems and Neural Networks", nameZh: "无序系统和神经网络", description: "Glasses and spin glasses; properties of random, aperiodic and quasiperiodic systems; transport in disordered media; localization; phenomena mediated by defects and disorder; neural networks" , descriptionZh: "玻璃和旋转玻璃；随机、非周期和准周期系统的性质；在无序介质中传输；本土化;由缺陷和紊乱引起的现象；神经网络" },
  { id: "cond-mat.mes-hall", parentId: "cond-mat", name: "Mesoscale and Nanoscale Physics", nameZh: "介观和纳米物理", description: "Semiconducting nanostructures: quantum dots, wires, and wells. Single electronics, spintronics, 2d electron gases, quantum Hall effect, nanotubes, graphene, plasmonic nanostructures" , descriptionZh: "半导体纳米结构：量子点、量子线和量子阱。单电子学、自旋电子学、二维电子气、量子霍尔效应、纳米管、石墨烯、等离子体纳米结构" },
  { id: "cond-mat.mtrl-sci", parentId: "cond-mat", name: "Materials Science", nameZh: "材料科学", description: "Techniques, synthesis, characterization, structure. Structural phase transitions, mechanical properties, phonons. Defects, adsorbates, interfaces" , descriptionZh: "技术、合成、表征、结构。结构相变、机械性能、声子。缺陷、吸附物、界面" },
  { id: "cond-mat.other", parentId: "cond-mat", name: "Other Condensed Matter", nameZh: "其他凝聚态物质", description: "Work in condensed matter that does not fit into the other cond-mat classifications" , descriptionZh: "在不属于其他条件垫分类的凝聚态物质中工作" },
  { id: "cond-mat.quant-gas", parentId: "cond-mat", name: "Quantum Gases", nameZh: "量子气体", description: "Ultracold atomic and molecular gases, Bose-Einstein condensation, Feshbach resonances, spinor condensates, optical lattices, quantum simulation with cold atoms and molecules, macroscopic interference phenomena" , descriptionZh: "超冷原子和分子气体、玻色-爱因斯坦凝聚、费什巴赫共振、旋量凝聚、光学晶格、冷原子和分子的量子模拟、宏观干涉现象" },
  { id: "cond-mat.soft", parentId: "cond-mat", name: "Soft Condensed Matter", nameZh: "软凝聚态物质", description: "Membranes, polymers, liquid crystals, glasses, colloids, granular matter" , descriptionZh: "膜、聚合物、液晶、玻璃、胶体、颗粒物质" },
  { id: "cond-mat.stat-mech", parentId: "cond-mat", name: "Statistical Mechanics", nameZh: "统计力学", description: "Phase transitions, thermodynamics, field theory, non-equilibrium phenomena, renormalization group and scaling, integrable models, turbulence" , descriptionZh: "相变、热力学、场论、非平衡现象、重正化群和标度、可积模型、湍流" },
  { id: "cond-mat.str-el", parentId: "cond-mat", name: "Strongly Correlated Electrons", nameZh: "强相关电子", description: "Quantum magnetism, non-Fermi liquids, spin liquids, quantum criticality, charge density waves, metal-insulator transitions" , descriptionZh: "量子磁性、非费米液体、自旋液体、量子临界性、电荷密度波、金属-绝缘体跃迁" },
  { id: "cond-mat.supr-con", parentId: "cond-mat", name: "Superconductivity", nameZh: "超导", description: "Superconductivity: theory, models, experiment. Superflow in helium" , descriptionZh: "超导：理论、模型、实验。氦气中的超流" },
  { id: "nlin.AO", parentId: "nlin", name: "Adaptation and Self-Organizing Systems", nameZh: "适应和自组织系统", description: "Adaptation, self-organizing systems, statistical physics, fluctuating systems, stochastic processes, interacting particle systems, machine learning" , descriptionZh: "适应、自组织系统、统计物理学、涨落系统、随机过程、相互作用粒子系统、机器学习" },
  { id: "nlin.CD", parentId: "nlin", name: "Chaotic Dynamics", nameZh: "混沌动力学", description: "Dynamical systems, chaos, quantum chaos, topological dynamics, cycle expansions, turbulence, propagation" , descriptionZh: "动力系统、混沌、量子混沌、拓扑动力学、循环展开、湍流、传播" },
  { id: "nlin.CG", parentId: "nlin", name: "Cellular Automata and Lattice Gases", nameZh: "元胞自动机和晶格气体", description: "Computational methods, time series analysis, signal processing, wavelets, lattice gases" , descriptionZh: "计算方法、时间序列分析、信号处理、小波、晶格气体" },
  { id: "nlin.PS", parentId: "nlin", name: "Pattern Formation and Solitons", nameZh: "模式形成和孤子", description: "Pattern formation, coherent structures, solitons" , descriptionZh: "图案形成、相干结构、孤子" },
  { id: "nlin.SI", parentId: "nlin", name: "Exactly Solvable and Integrable Systems", nameZh: "精确可解可积系统", description: "Exactly solvable systems, integrable PDEs, integrable ODEs, Painleve analysis, integrable discrete maps, solvable lattice models, integrable quantum systems" , descriptionZh: "精确可解系统、可积偏微分方程、可积常微分方程、Painleve 分析、可积离散映射、可解晶格模型、可积量子系统" },
  { id: "physics.acc-ph", parentId: "physics", name: "Accelerator Physics", nameZh: "加速器物理", description: "Accelerator theory and simulation. Accelerator technology. Accelerator experiments. Beam Physics. Accelerator design and optimization. Advanced accelerator concepts. Radiation sources including synchrotron light sources and free electron lasers. Applications of accelerators." , descriptionZh: "加速器理论与模拟。加速器技术。加速器实验。梁物理学。加速器设计与优化。先进的加速器概念。辐射源包括同步加速器光源和自由电子激光器。加速器的应用。" },
  { id: "physics.ao-ph", parentId: "physics", name: "Atmospheric and Oceanic Physics", nameZh: "大气和海洋物理", description: "Atmospheric and oceanic physics and physical chemistry, biogeophysics, and climate science" , descriptionZh: "大气和海洋物理与物理化学、生物地球物理学和气候科学" },
  { id: "physics.app-ph", parentId: "physics", name: "Applied Physics", nameZh: "应用物理", description: "Applications of physics to new technology, including electronic devices, optics, photonics, microwaves, spintronics, advanced materials, metamaterials, nanotechnology, and energy sciences." , descriptionZh: "物理学在新技术中的应用，包括电子设备、光学、光子学、微波、自旋电子学、先进材料、超材料、纳米技术和能源科学。" },
  { id: "physics.atm-clus", parentId: "physics", name: "Atomic and Molecular Clusters", nameZh: "原子和分子簇", description: "Atomic and molecular clusters, nanoparticles: geometric, electronic, optical, chemical, magnetic properties, shell structure, phase transitions, optical spectroscopy, mass spectrometry, photoelectron spectroscopy, ionization potential, electron affinity, interaction with intense light pulses, electron diffraction, light scattering, ab initio calculations, DFT theory, fragmentation, Coulomb explosion, hydrodynamic expansion." , descriptionZh: "原子和分子簇、纳米粒子：几何、电子、光学、化学、磁性、壳结构、相变、光谱、质谱、光电子能谱、电离势、电子亲和力、与强光脉冲的相互作用、电子衍射、光散射、从头计算、DFT理论、碎裂、库仑爆炸、流体动力学膨胀。" },
  { id: "physics.atom-ph", parentId: "physics", name: "Atomic Physics", nameZh: "原子物理学", description: "Atomic and molecular structure, spectra, collisions, and data. Atoms and molecules in external fields. Molecular dynamics and coherent and optical control. Cold atoms and molecules. Cold collisions. Optical lattices." , descriptionZh: "原子和分子结构、光谱、碰撞和数据。外场中的原子和分子。分子动力学以及相干和光学控制。冷原子和分子。冰冷的碰撞。光学晶格。" },
  { id: "physics.bio-ph", parentId: "physics", name: "Biological Physics", nameZh: "生物物理学", description: "Molecular biophysics, cellular biophysics, neurological biophysics, membrane biophysics, single-molecule biophysics, ecological biophysics, quantum phenomena in biological systems (quantum biophysics), theoretical biophysics, molecular dynamics/modeling and simulation, game theory, biomechanics, bioinformatics, microorganisms, virology, evolution, biophysical methods." , descriptionZh: "分子生物物理学、细胞生物物理学、神经生物物理学、膜生物物理学、单分子生物物理学、生态生物物理学、生物系统中的量子现象（量子生物物理学）、理论生物物理学、分子动力学/建模与模拟、博弈论、生物力学、生物信息学、微生物、病毒学、进化、生物物理方法。" },
  { id: "physics.chem-ph", parentId: "physics", name: "Chemical Physics", nameZh: "化学物理", description: "Experimental, computational, and theoretical physics of atoms, molecules, and clusters - Classical and quantum description of states, processes, and dynamics; spectroscopy, electronic structure, conformations, reactions, interactions, and phases. Chemical thermodynamics. Disperse systems. High pressure chemistry. Solid state chemistry. Surface and interface chemistry." , descriptionZh: "原子、分子和团簇的实验、计算和理论物理——状态、过程和动力学的经典和量子描述；光谱学、电子结构、构象、反应、相互作用和相。化学热力学。分散系统。高压化学。固态化学。表面和界面化学。" },
  { id: "physics.class-ph", parentId: "physics", name: "Classical Physics", nameZh: "经典物理学", description: "Newtonian and relativistic dynamics; many particle systems; planetary motions; chaos in classical dynamics. Maxwell's equations and dynamics of charged systems and electromagnetic forces in materials. Vibrating systems such as membranes and cantilevers; optomechanics. Classical waves, including acoustics and elasticity; physics of music and musical instruments. Classical thermodynamics and heat flow problems." , descriptionZh: "牛顿和相对论动力学；许多粒子系统；行星运动；经典动力学中的混沌。麦克斯韦方程组和带电系统动力学以及材料中的电磁力。振动系统，例如膜和悬臂；光力学。经典波，包括声学和弹性；音乐和乐器物理学。经典热力学和热流问题。" },
  { id: "physics.comp-ph", parentId: "physics", name: "Computational Physics", nameZh: "计算物理", description: "All aspects of computational science applied to physics." , descriptionZh: "计算科学的各个方面都应用于物理学。" },
  { id: "physics.data-an", parentId: "physics", name: "Data Analysis, Statistics and Probability", nameZh: "数据分析、统计和概率", description: "Methods, software and hardware for physics data analysis: data processing and storage; measurement methodology; statistical and mathematical aspects such as parametrization and uncertainties." , descriptionZh: "物理数据分析的方法、软件和硬件：数据处理和存储；测量方法；统计和数学方面，例如参数化和不确定性。" },
  { id: "physics.ed-ph", parentId: "physics", name: "Physics Education", nameZh: "物理教育", description: "Report of results of a research study, laboratory experience, assessment or classroom practice that represents a way to improve teaching and learning in physics. Also, report on misconceptions of students, textbook errors, and other similar information relative to promoting physics understanding." , descriptionZh: "研究报告、实验室经验、评估或课堂实践的结果，代表了改进物理教学的一种方法。此外，报告学生的误解、教科书错误以及其他与促进物理理解相关的类似信息。" },
  { id: "physics.flu-dyn", parentId: "physics", name: "Fluid Dynamics", nameZh: "流体动力学", description: "Turbulence, instabilities, incompressible/compressible flows, reacting flows. Aero/hydrodynamics, fluid-structure interactions, acoustics. Biological fluid dynamics, micro/nanofluidics, interfacial phenomena. Complex fluids, suspensions and granular flows, porous media flows. Geophysical flows, thermoconvective and stratified flows. Mathematical and computational methods for fluid dynamics, fluid flow models, experimental techniques." , descriptionZh: "湍流、不稳定性、不可压缩/可压缩流、反应流。空气/流体动力学、流体-结构相互作用、声学。生物流体动力学、微/纳米流体、界面现象。复杂流体、悬浮液和颗粒流、多孔介质流。地球物理流、热对流和分层流。流体动力学、流体流动模型、实验技术的数学和计算方法。" },
  { id: "physics.gen-ph", parentId: "physics", name: "General Physics", nameZh: "普通物理", description: "Foundational, cross-disciplinary and general physics that does not fit a specialized category — classical mechanics, broad physical principles, and general theoretical frameworks." , descriptionZh: "基础、跨学科和一般物理学，不属于专门类别——经典力学、广泛的物理原理和一般理论框架。" },
  { id: "physics.geo-ph", parentId: "physics", name: "Geophysics", nameZh: "地球物理学", description: "Atmospheric physics. Biogeosciences. Computational geophysics. Geographic location. Geoinformatics. Geophysical techniques. Hydrospheric geophysics. Magnetospheric physics. Mathematical geophysics. Planetology. Solar system. Solid earth geophysics. Space plasma physics. Mineral physics. High pressure physics." , descriptionZh: "大气物理学。生物地球科学。计算地球物理学。地理位置。地理信息学。地球物理技术。水圈地球物理学。磁层物理学。数学地球物理学。行星学。太阳能系统。固体地球地球物理学。空间等离子体物理学。矿物物理学。高压物理。" },
  { id: "physics.hist-ph", parentId: "physics", name: "History and Philosophy of Physics", nameZh: "物理学史与哲学", description: "History and philosophy of all branches of physics, astrophysics, and cosmology, including appreciations of physicists." , descriptionZh: "物理学、天体物理学和宇宙学所有分支的历史和哲学，包括物理学家的欣赏。" },
  { id: "physics.ins-det", parentId: "physics", name: "Instrumentation and Detectors", nameZh: "仪器仪表和探测器", description: "Instrumentation and Detectors for research in natural science, including optical, molecular, atomic, nuclear and particle physics instrumentation and the associated electronics, services, infrastructure and control equipment." , descriptionZh: "用于自然科学研究的仪器和探测器，包括光学、分子、原子、核和粒子物理仪器以及相关的电子、服务、基础设施和控制设备。" },
  { id: "physics.med-ph", parentId: "physics", name: "Medical Physics", nameZh: "医学物理", description: "Radiation therapy. Radiation dosimetry. Biomedical imaging modelling. Reconstruction, processing, and analysis. Biomedical system modelling and analysis. Health physics. New imaging or therapy modalities." , descriptionZh: "放射治疗。辐射剂量测定。生物医学成像建模。重建、处理和分析。生物医学系统建模和分析。健康物理学。新的成像或治疗方式。" },
  { id: "physics.optics", parentId: "physics", name: "Optics", nameZh: "光学", description: "Adaptive optics. Astronomical optics. Atmospheric optics. Biomedical optics. Cardinal points. Collimation. Doppler effect. Fiber optics. Fourier optics. Geometrical optics (Gradient index optics. Holography. Infrared optics. Integrated optics. Laser applications. Laser optical systems. Lasers. Light amplification. Light diffraction. Luminescence. Microoptics. Nano optics. Ocean optics. Optical computing. Optical devices. Optical imaging. Optical materials. Optical metrology. Optical microscopy. Optical properties. Optical signal processing. Optical testing techniques. Optical wave propagation. Paraxial optics. Photoabsorption. Photoexcitations. Physical optics. Physiological optics. Quantum optics. Segmented optics. Spectra. Statistical optics. Surface optics. Ultrafast optics. Wave optics. X-ray optics." , descriptionZh: "自适应光学。天文光学。大气光学。生物医学光学。基点。准直。多普勒效应。光纤。傅里叶光学。几何光学（梯度折射率光学、全息术、红外光学、集成光学、激光应用、激光光学系统、激光器、光放大、光衍射、发光、微光学、纳米光学、海洋光学、光学计算、光学器件、光学成像、光学材料、光学计量、光学显微镜、光学特性、光信号处理、光学测试技术、光波传播、近轴光学、光吸收、光激发、物理量子光学。" },
  { id: "physics.plasm-ph", parentId: "physics", name: "Plasma Physics", nameZh: "等离子体物理", description: "Fundamental plasma physics. Magnetically Confined Plasmas (includes magnetic fusion energy research). High Energy Density Plasmas (inertial confinement plasmas, laser-plasma interactions). Ionospheric, Heliophysical, and Astrophysical plasmas (includes sun and solar system plasmas). Lasers, Accelerators, and Radiation Generation. Low temperature plasmas and plasma applications (include dusty plasmas, semiconductor etching, plasma-based nanotechnology, medical applications). Plasma Diagnostics, Engineering and Enabling Technologies (includes fusion reactor design, heating systems, diagnostics, experimental techniques)" , descriptionZh: "基础等离子体物理学。磁约束等离子体（包括磁聚变能研究）。高能量密度等离子体（惯性约束等离子体、激光等离子体相互作用）。电离层、太阳物理和天体物理等离子体（包括太阳和太阳系等离子体）。激光器、加速器和辐射产生。低温等离子体和等离子体应用（包括尘埃等离子体、半导体蚀刻、基于等离子体的纳米技术、医疗应用）。等离子体诊断、工程和使能技术（包括聚变反应堆设计、加热系统、诊断、实验技术）" },
  { id: "physics.pop-ph", parentId: "physics", name: "Popular Physics", nameZh: "大众物理", description: "Physics written for a general audience: expository and pedagogical articles, science communication, and accessible overviews of physics topics for non-specialists." , descriptionZh: "为普通读者撰写的物理学：说明性和教学文章、科学传播以及针对非专业人士的物理主题的易于理解的概述。" },
  { id: "physics.soc-ph", parentId: "physics", name: "Physics and Society", nameZh: "物理与社会", description: "Structure, dynamics and collective behavior of societies and groups (human or otherwise). Quantitative analysis of social networks and other complex networks. Physics and engineering of infrastructure and systems of broad societal impact (e.g., energy grids, transportation networks)." , descriptionZh: "社会和群体（人类或其他）的结构、动态和集体行为。社交网络和其他复杂网络的定量分析。具有广泛社会影响的基础设施和系统（例如能源网、交通网络）的物理和工程。" },
  { id: "physics.space-ph", parentId: "physics", name: "Space Physics", nameZh: "空间物理学", description: "Space plasma physics. Heliophysics. Space weather. Planetary magnetospheres, ionospheres and magnetotail. Auroras. Interplanetary space. Cosmic rays. Synchrotron radiation. Radio astronomy." , descriptionZh: "空间等离子体物理学。太阳物理学。太空天气。行星磁层、电离层和磁尾。极光。行星际空间。宇宙射线。同步辐射。射电天文学。" },
  { id: "q-bio.BM", parentId: "q-bio", name: "Biomolecules", nameZh: "生物分子", description: "DNA, RNA, proteins, lipids, etc.; molecular structures and folding kinetics; molecular interactions; single-molecule manipulation." , descriptionZh: "DNA、RNA、蛋白质、脂质等；分子结构和折叠动力学；分子相互作用；单分子操纵。" },
  { id: "q-bio.CB", parentId: "q-bio", name: "Cell Behavior", nameZh: "细胞行为", description: "Cell-cell signaling and interaction; morphogenesis and development; apoptosis; bacterial conjugation; viral-host interaction; immunology" , descriptionZh: "细胞间信号传导和相互作用；形态发生和发育；细胞凋亡；细菌接合；病毒与宿主的相互作用；免疫学" },
  { id: "q-bio.GN", parentId: "q-bio", name: "Genomics", nameZh: "基因组学", description: "DNA sequencing and assembly; gene and motif finding; RNA editing and alternative splicing; genomic structure and processes (replication, transcription, methylation, etc); mutational processes." , descriptionZh: "DNA测序和组装；基因和基序发现； RNA编辑和选择性剪接；基因组结构和过程（复制、转录、甲基化等）；突变过程。" },
  { id: "q-bio.MN", parentId: "q-bio", name: "Molecular Networks", nameZh: "分子网络", description: "Gene regulation, signal transduction, proteomics, metabolomics, gene and enzymatic networks" , descriptionZh: "基因调控、信号转导、蛋白质组学、代谢组学、基因和酶网络" },
  { id: "q-bio.NC", parentId: "q-bio", name: "Neurons and Cognition", nameZh: "神经元和认知", description: "Synapse, cortex, neuronal dynamics, neural network, sensorimotor control, behavior, attention" , descriptionZh: "突触、皮层、神经元动力学、神经网络、感觉运动控制、行为、注意力" },
  { id: "q-bio.OT", parentId: "q-bio", name: "Other Quantitative Biology", nameZh: "其他定量生物学", description: "Work in quantitative biology that does not fit into the other q-bio classifications" , descriptionZh: "从事不属于其他 q-bio 分类的定量生物学工作" },
  { id: "q-bio.PE", parentId: "q-bio", name: "Populations and Evolution", nameZh: "种群与进化", description: "Population dynamics, spatio-temporal and epidemiological models, dynamic speciation, co-evolution, biodiversity, foodwebs, aging; molecular evolution and phylogeny; directed evolution; origin of life" , descriptionZh: "人口动态、时空和流行病学模型、动态物种形成、共同进化、生物多样性、食物网、老龄化；分子进化和系统发育；定向进化；生命的起源" },
  { id: "q-bio.QM", parentId: "q-bio", name: "Quantitative Methods", nameZh: "定量方法", description: "All experimental, numerical, statistical and mathematical contributions of value to biology" , descriptionZh: "所有对生物学有价值的实验、数值、统计和数学贡献" },
  { id: "q-bio.SC", parentId: "q-bio", name: "Subcellular Processes", nameZh: "亚细胞过程", description: "Assembly and control of subcellular structures (channels, organelles, cytoskeletons, capsules, etc.); molecular motors, transport, subcellular localization; mitosis and meiosis" , descriptionZh: "亚细胞结构（通道、细胞器、细胞骨架、胶囊等）的组装和控制；分子马达、运输、亚细胞定位；有丝分裂和减数分裂" },
  { id: "q-bio.TO", parentId: "q-bio", name: "Tissues and Organs", nameZh: "组织和器官", description: "Blood flow in vessels, biomechanics of bones, electrical waves, endocrine system, tumor growth" , descriptionZh: "血管血流、骨骼生物力学、电波、内分泌系统、肿瘤生长" },
  { id: "q-fin.CP", parentId: "q-fin", name: "Computational Finance", nameZh: "计算金融", description: "Computational methods, including Monte Carlo, PDE, lattice and other numerical methods with applications to financial modeling" , descriptionZh: "计算方法，包括蒙特卡洛、偏微分方程、格子和其他应用于金融建模的数值方法" },
  { id: "q-fin.EC", parentId: "q-fin", name: "Economics", nameZh: "经济学", description: "q-fin.EC is an alias for econ.GN. Economics, including micro and macro economics, international economics, theory of the firm, labor economics, and other economic topics outside finance" , descriptionZh: "q-fin.EC 是 econ.GN 的别名。经济学，包括微观和宏观经济学、国际经济学、公司理论、劳动经济学以及金融以外的其他经济主题" },
  { id: "q-fin.GN", parentId: "q-fin", name: "General Finance", nameZh: "一般财务", description: "Development of general quantitative methodologies with applications in finance" , descriptionZh: "开发通用定量方法及其在金融中的应用" },
  { id: "q-fin.MF", parentId: "q-fin", name: "Mathematical Finance", nameZh: "数学金融", description: "Mathematical and analytical methods of finance, including stochastic, probabilistic and functional analysis, algebraic, geometric and other methods" , descriptionZh: "金融数学和分析方法，包括随机、概率和泛函分析、代数、几何和其他方法" },
  { id: "q-fin.PM", parentId: "q-fin", name: "Portfolio Management", nameZh: "投资组合管理", description: "Security selection and optimization, capital allocation, investment strategies and performance measurement" , descriptionZh: "证券选择和优化、资本配置、投资策略和绩效衡量" },
  { id: "q-fin.PR", parentId: "q-fin", name: "Pricing of Securities", nameZh: "证券定价", description: "Valuation and hedging of financial securities, their derivatives, and structured products" , descriptionZh: "金融证券、其衍生品和结构性产品的估值和对冲" },
  { id: "q-fin.RM", parentId: "q-fin", name: "Risk Management", nameZh: "风险管理", description: "Measurement and management of financial risks in trading, banking, insurance, corporate and other applications" , descriptionZh: "贸易、银行、保险、企业和其他应用中金融风险的测量和管理" },
  { id: "q-fin.ST", parentId: "q-fin", name: "Statistical Finance", nameZh: "统计金融", description: "Statistical, econometric and econophysics analyses with applications to financial markets and economic data" , descriptionZh: "统计、计量经济学和经济物理学分析及其在金融市场和经济数据中的应用" },
  { id: "q-fin.TR", parentId: "q-fin", name: "Trading and Market Microstructure", nameZh: "交易和市场微观结构", description: "Market microstructure, liquidity, exchange and auction design, automated trading, agent-based modeling and market-making" , descriptionZh: "市场微观结构、流动性、交易和拍卖设计、自动化交易、基于代理的建模和做市" },
  { id: "stat.AP", parentId: "stat", name: "Applications", nameZh: "应用领域", description: "Biology, Education, Epidemiology, Engineering, Environmental Sciences, Medical, Physical Sciences, Quality Control, Social Sciences" , descriptionZh: "生物学、教育学、流行病学、工程、环境科学、医学、物理科学、质量控制、社会科学" },
  { id: "stat.CO", parentId: "stat", name: "Computation", nameZh: "计算", description: "Algorithms, Simulation, Visualization" , descriptionZh: "算法、模拟、可视化" },
  { id: "stat.ME", parentId: "stat", name: "Methodology", nameZh: "方法论", description: "Design, Surveys, Model Selection, Multiple Testing, Multivariate Methods, Signal and Image Processing, Time Series, Smoothing, Spatial Statistics, Survival Analysis, Nonparametric and Semiparametric Methods" , descriptionZh: "设计、调查、模型选择、多重测试、多元方法、信号和图像处理、时间序列、平滑、空间统计、生存分析、非参数和半参数方法" },
  { id: "stat.ML", parentId: "stat", name: "Machine Learning", nameZh: "机器学习", description: "Covers machine learning papers (supervised, unsupervised, semi-supervised learning, graphical models, reinforcement learning, bandits, high dimensional inference, etc.) with a statistical or theoretical grounding" , descriptionZh: "涵盖具有统计或理论基础的机器学习论文（监督、无监督、半监督学习、图模型、强化学习、强盗、高维推理等）" },
  { id: "stat.OT", parentId: "stat", name: "Other Statistics", nameZh: "其他统计数据", description: "Work in statistics that does not fit into the other stat classifications" , descriptionZh: "从事不属于其他统计分类的统计工作" },
  { id: "stat.TH", parentId: "stat", name: "Statistics Theory", nameZh: "统计理论", description: "stat.TH is an alias for math.ST. Asymptotics, Bayesian Inference, Decision Theory, Estimation, Foundations, Inference, Testing." , descriptionZh: "stat.TH 是 math.ST 的别名。渐近学、贝叶斯推理、决策理论、估计、基础、推理、测试。" },

  // Humanities — not part of arXiv; added so Papex can cover liberal arts.
  { id: "hum", parentId: null, name: "Humanities", nameZh: "人文学科", description: "All areas of the humanities, including philosophy, history, literature, language, society, politics, law, art, education, and culture." , descriptionZh: "人文学科的各个领域，包括哲学、历史、文学、语言、社会、政治、法律、艺术、教育和文化。" },
  { id: "hum.phil", parentId: "hum", name: "Philosophy", nameZh: "哲学", description: "All areas of philosophy, including metaphysics, epistemology, ethics, logic, aesthetics, philosophy of mind, and political philosophy." , descriptionZh: "哲学的所有领域，包括形而上学、认识论、伦理学、逻辑学、美学、心灵哲学和政治哲学。" },
  { id: "hum.hist", parentId: "hum", name: "History", nameZh: "历史", description: "All areas of history, including political, social, economic, cultural, intellectual, and global history." , descriptionZh: "所有历史领域，包括政治、社会、经济、文化、知识和全球历史。" },
  { id: "hum.lit", parentId: "hum", name: "Literature", nameZh: "文学", description: "Literary studies, including literary theory, comparative literature, poetry, fiction, drama, and textual criticism." , descriptionZh: "文学研究，包括文学理论、比较文学、诗歌、小说、戏剧和考证。" },
  { id: "hum.ling", parentId: "hum", name: "Linguistics", nameZh: "语言学", description: "The scientific study of language, including phonetics, phonology, syntax, semantics, pragmatics, historical linguistics, and sociolinguistics." , descriptionZh: "对语言的科学研究，包括语音学、音系学、句法、语义、语用学、历史语言学和社会语言学。" },
  { id: "hum.soc", parentId: "hum", name: "Sociology", nameZh: "社会学", description: "The study of society, social institutions, social relationships, stratification, culture, and social change." , descriptionZh: "对社会、社会制度、社会关系、分层、文化和社会变革的研究。" },
  { id: "hum.pol", parentId: "hum", name: "Political Science", nameZh: "政治学", description: "The study of politics and government, including political theory, comparative politics, international relations, and public policy." , descriptionZh: "政治和政府研究，包括政治理论、比较政治、国际关系和公共政策。" },
  { id: "hum.law", parentId: "hum", name: "Law", nameZh: "法律", description: "Legal studies, including jurisprudence, constitutional law, international law, criminal law, and legal theory." , descriptionZh: "法律研究，包括法理学、宪法、国际法、刑法和法律理论。" },
  { id: "hum.art", parentId: "hum", name: "Arts", nameZh: "艺术", description: "Art history, visual culture, musicology, performance studies, and the theory and criticism of the arts." , descriptionZh: "艺术史、视觉文化、音乐学、表演研究以及艺术理论和批评。" },
  { id: "hum.edu", parentId: "hum", name: "Education", nameZh: "教育", description: "Educational theory and practice, including pedagogy, curriculum, educational policy, learning sciences, and assessment." , descriptionZh: "教育理论和实践，包括教育学、课程、教育政策、学习科学和评估。" },
  { id: "hum.anth", parentId: "hum", name: "Anthropology", nameZh: "人类学", description: "The study of humanity, including cultural and social anthropology and biological anthropology." , descriptionZh: "对人类的研究，包括文化和社会人类学以及生物人类学。" },
  { id: "hum.psy", parentId: "hum", name: "Psychology", nameZh: "心理学", description: "The scientific study of mind and behavior, including cognitive, social, developmental, clinical, and personality psychology." , descriptionZh: "对心理和行为的科学研究，包括认知心理学、社会心理学、发展心理学、临床心理学和人格心理学。" },
  { id: "hum.rel", parentId: "hum", name: "Religious Studies", nameZh: "宗教研究", description: "The academic study of religion, including comparative religion, theology, sacred texts, and religious history." , descriptionZh: "宗教的学术研究，包括比较宗教、神学、神圣文本和宗教历史。" },
  { id: "hum.arch", parentId: "hum", name: "Archaeology", nameZh: "考古学", description: "The study of past human societies through material remains, including method, fieldwork, and interpretation." , descriptionZh: "通过物质遗骸研究过去的人类社会，包括方法、实地考察和解释。" },
  { id: "hum.com", parentId: "hum", name: "Communication and Media", nameZh: "传播与媒体", description: "Media studies, journalism, rhetoric, discourse analysis, and the study of communication in society." , descriptionZh: "媒体研究、新闻学、修辞学、话语分析以及社会传播研究。" },
  { id: "hum.geo", parentId: "hum", name: "Human Geography", nameZh: "人文地理学", description: "The study of people, places, and their relationships, including urban, cultural, economic, and social geography." , descriptionZh: "对人、地点及其关系的研究，包括城市、文化、经济和社会地理。" },

  // Chemistry — one of the core natural sciences; no arXiv equivalent.
  { id: "chem", parentId: null, name: "Chemistry", nameZh: "化学", description: "All areas of chemistry, including organic, inorganic, physical, analytical, and theoretical chemistry." , descriptionZh: "化学的所有领域，包括有机化学、无机化学、物理化学、分析化学和理论化学。" },
  { id: "chem.org", parentId: "chem", name: "Organic Chemistry", nameZh: "有机化学", description: "Structure, synthesis, and reactivity of carbon-containing compounds; mechanisms, catalysis, and natural products." , descriptionZh: "含碳化合物的结构、合成和反应性；机制、催化和天然产物。" },
  { id: "chem.inorg", parentId: "chem", name: "Inorganic Chemistry", nameZh: "无机化学", description: "Synthesis and properties of inorganic and organometallic compounds; coordination, main-group, and solid-state chemistry." , descriptionZh: "无机和有机金属化合物的合成与性能；配位、主族和固态化学。" },
  { id: "chem.phys", parentId: "chem", name: "Physical Chemistry", nameZh: "物理化学", description: "Thermodynamics, kinetics, spectroscopy, quantum chemistry, and the physical principles underlying chemical processes." , descriptionZh: "热力学、动力学、光谱学、量子化学以及化学过程的物理原理。" },
  { id: "chem.anal", parentId: "chem", name: "Analytical Chemistry", nameZh: "分析化学", description: "Qualitative and quantitative analysis, instrumentation, separations, sensors, and measurement science." , descriptionZh: "定性和定量分析、仪器仪表、分离、传感器和测量科学。" },
  { id: "chem.bio", parentId: "chem", name: "Biochemistry", nameZh: "生物化学", description: "Chemical processes and substances in living organisms; enzymes, metabolism, and molecular biology at the chemical level." , descriptionZh: "生物体中的化学过程和物质；化学水平上的酶、新陈代谢和分子生物学。" },
  { id: "chem.mtrl", parentId: "chem", name: "Materials Chemistry", nameZh: "材料化学", description: "Design, synthesis, and characterization of materials with targeted chemical and physical properties." , descriptionZh: "具有目标化学和物理特性的材料的设计、合成和表征。" },
  { id: "chem.theo", parentId: "chem", name: "Theoretical and Computational Chemistry", nameZh: "理论与计算化学", description: "Quantum, statistical, and computational methods for modeling molecular structure, dynamics, and reactivity." , descriptionZh: "用于模拟分子结构、动力学和反应性的量子、统计和计算方法。" },
  { id: "chem.env", parentId: "chem", name: "Environmental Chemistry", nameZh: "环境化学", description: "Chemical phenomena in the environment, pollution, remediation, and the fate of chemicals in air, water, and soil." , descriptionZh: "环境中的化学现象、污染、修复以及空气、水和土壤中化学物质的归宿。" },

  // Earth & Environmental Sciences.
  { id: "earth", parentId: null, name: "Earth and Environmental Sciences", nameZh: "地球与环境科学", description: "All areas of earth, atmospheric, oceanic, and environmental science." , descriptionZh: "地球、大气、海洋和环境科学的所有领域。" },
  { id: "earth.geo", parentId: "earth", name: "Geology", nameZh: "地质学", description: "Mineralogy, petrology, structural geology, stratigraphy, volcanology, and the history of the solid Earth." , descriptionZh: "矿物学、岩石学、构造地质学、地层学、火山学和固体地球的历史。" },
  { id: "earth.atm", parentId: "earth", name: "Atmospheric Science", nameZh: "大气科学", description: "Meteorology, atmospheric chemistry and physics, weather, and the dynamics of the atmosphere." , descriptionZh: "气象学、大气化学和物理学、天气和大气动力学。" },
  { id: "earth.oce", parentId: "earth", name: "Oceanography", nameZh: "海洋学", description: "Physical, chemical, and biological oceanography; marine circulation, biogeochemistry, and coastal systems." , descriptionZh: "物理、化学和生物海洋学；海洋环流、生物地球化学和沿海系统。" },
  { id: "earth.env", parentId: "earth", name: "Environmental Science", nameZh: "环境科学", description: "Interdisciplinary study of environmental systems, ecology, sustainability, and human impacts on the planet." , descriptionZh: "环境系统、生态学、可持续性和人类对地球影响的跨学科研究。" },
  { id: "earth.clim", parentId: "earth", name: "Climate Science", nameZh: "气候科学", description: "Climate dynamics, paleoclimate, climate modeling, and the physical basis of climate change." , descriptionZh: "气候动力学、古气候、气候模型和气候变化的物理基础。" },
  { id: "earth.paleo", parentId: "earth", name: "Paleontology", nameZh: "古生物学", description: "Fossils, extinct life, and the evolutionary history of organisms through geologic time." , descriptionZh: "化石、灭绝的生命以及地质时期生物体的进化史。" },

  // Medicine & Health Sciences.
  { id: "med", parentId: null, name: "Medicine and Health Sciences", nameZh: "医学与健康科学", description: "All areas of medicine, public health, and the health sciences." , descriptionZh: "医学、公共卫生和健康科学的所有领域。" },
  { id: "med.clin", parentId: "med", name: "Clinical Medicine", nameZh: "临床医学", description: "Internal medicine, diagnosis, therapeutics, and the practice of patient care across specialties." , descriptionZh: "内科、诊断、治疗以及跨专业的患者护理实践。" },
  { id: "med.pub", parentId: "med", name: "Public Health", nameZh: "公共卫生", description: "Population health, health policy, disease prevention, and health systems." , descriptionZh: "人口健康、卫生政策、疾病预防和卫生系统。" },
  { id: "med.epid", parentId: "med", name: "Epidemiology", nameZh: "流行病学", description: "Distribution and determinants of health and disease in populations; outbreak and surveillance science." , descriptionZh: "人群健康和疾病的分布及其决定因素；爆发和监测科学。" },
  { id: "med.phar", parentId: "med", name: "Pharmacology and Pharmacy", nameZh: "药理学与药学", description: "Drug action, pharmacokinetics, pharmacodynamics, and the science of medication development and use." , descriptionZh: "药物作用、药代动力学、药效学以及药物开发和使用的科学。" },
  { id: "med.nurs", parentId: "med", name: "Nursing", nameZh: "护理", description: "Nursing science, patient care, and clinical practice across care settings." , descriptionZh: "护理科学、患者护理和跨护理环境的临床实践。" },
  { id: "med.surg", parentId: "med", name: "Surgery", nameZh: "外科手术", description: "Surgical specialties, operative technique, perioperative care, and surgical outcomes." , descriptionZh: "外科专业、手术技术、围手术期护理和手术结果。" },
  { id: "med.bio", parentId: "med", name: "Biomedical Sciences", nameZh: "生物医学科学", description: "Laboratory and translational research underpinning medicine, including molecular, cellular, and systems biomedicine." , descriptionZh: "支持医学的实验室和转化研究，包括分子、细胞和系统生物医学。" },
  { id: "med.psych", parentId: "med", name: "Psychiatry", nameZh: "精神病学", description: "Diagnosis, treatment, and study of mental disorders; clinical and neurobiological aspects (cf. hum.psy for psychology)." , descriptionZh: "精神障碍的诊断、治疗和研究；临床和神经生物学方面（参见心理学的 hum.psy）。" },
  { id: "med.vet", parentId: "med", name: "Veterinary Medicine", nameZh: "兽医学", description: "Animal health, disease, and clinical care of domesticated and wild species." , descriptionZh: "驯养和野生物种的动物健康、疾病和临床护理。" },

  // Engineering (electrical & computer engineering are covered by eess and cs).
  { id: "eng", parentId: null, name: "Engineering", nameZh: "工程", description: "All areas of engineering other than electrical and computer engineering." , descriptionZh: "除电气和计算机工程之外的所有工程领域。" },
  { id: "eng.mech", parentId: "eng", name: "Mechanical Engineering", nameZh: "机械工业", description: "Mechanics, dynamics, thermodynamics, fluid and solid mechanics, and mechanical design and manufacturing." , descriptionZh: "力学、动力学、热力学、流体和固体力学以及机械设计和制造。" },
  { id: "eng.civ", parentId: "eng", name: "Civil Engineering", nameZh: "土木工程", description: "Structural, geotechnical, transportation, and construction engineering; infrastructure and the built environment." , descriptionZh: "结构、岩土、交通和建筑工程；基础设施和建筑环境。" },
  { id: "eng.chem", parentId: "eng", name: "Chemical Engineering", nameZh: "化工", description: "Process engineering, reaction engineering, separations, and the application of chemistry at industrial scale." , descriptionZh: "过程工程、反应工程、分离以及工业规模的化学应用。" },
  { id: "eng.aero", parentId: "eng", name: "Aerospace Engineering", nameZh: "航空航天工程", description: "Aerodynamics, propulsion, flight mechanics, and the design of aircraft and spacecraft." , descriptionZh: "空气动力学、推进力、飞行力学以及飞机和航天器的设计。" },
  { id: "eng.bme", parentId: "eng", name: "Biomedical Engineering", nameZh: "生物医学工程", description: "Engineering approaches to medicine and biology, including devices, implants, imaging, and tissue engineering." , descriptionZh: "医学和生物学的工程方法，包括设备、植入物、成像和组织工程。" },
  { id: "eng.env", parentId: "eng", name: "Environmental Engineering", nameZh: "环境工程", description: "Water, waste, and air treatment; remediation; and engineering for environmental protection and sustainability." , descriptionZh: "水、废物和空气处理；补救；以及环境保护和可持续发展工程。" },
  { id: "eng.mat", parentId: "eng", name: "Materials Engineering", nameZh: "材料工程", description: "Processing, properties, and design of engineering materials, including metals, ceramics, polymers, and composites." , descriptionZh: "工程材料（包括金属、陶瓷、聚合物和复合材料）的加工、性能和设计。" },
  { id: "eng.ind", parentId: "eng", name: "Industrial and Systems Engineering", nameZh: "工业与系统工程", description: "Optimization, operations research, human factors, quality, and production systems." , descriptionZh: "优化、运筹学、人为因素、质量和生产系统。" },

  // Biological Sciences — broader life sciences complementing q-bio (quantitative biology).
  { id: "bio", parentId: null, name: "Biological Sciences", nameZh: "生物科学", description: "The full range of biology beyond quantitative methods, from molecules to ecosystems." , descriptionZh: "超越定量方法的全方位生物学，从分子到生态系统。" },
  { id: "bio.mol", parentId: "bio", name: "Molecular Biology", nameZh: "分子生物学", description: "Molecular basis of cellular processes, gene expression, and the structure and function of biomolecules." , descriptionZh: "细胞过程、基因表达以及生物分子的结构和功能的分子基础。" },
  { id: "bio.cell", parentId: "bio", name: "Cell Biology", nameZh: "细胞生物学", description: "Structure, function, and behavior of cells; organelles, signaling, and the cell cycle." , descriptionZh: "细胞的结构、功能和行为；细胞器、信号传导和细胞周期。" },
  { id: "bio.gen", parentId: "bio", name: "Genetics", nameZh: "遗传学", description: "Heredity, genes, genomes, and the variation and transmission of genetic information." , descriptionZh: "遗传、基因、基因组以及遗传信息的变异和传递。" },
  { id: "bio.phys", parentId: "bio", name: "Physiology", nameZh: "生理", description: "Function of organisms and their systems, tissues, and organs under normal and perturbed conditions." , descriptionZh: "正常和扰动条件下生物体及其系统、组织和器官的功能。" },
  { id: "bio.ecol", parentId: "bio", name: "Ecology", nameZh: "生态", description: "Interactions of organisms with each other and their environment; ecosystems, communities, and biodiversity." , descriptionZh: "生物体之间及其环境的相互作用；生态系统、社区和生物多样性。" },
  { id: "bio.zoo", parentId: "bio", name: "Zoology", nameZh: "动物学", description: "Animals, their structure, classification, behavior, and distribution." , descriptionZh: "动物，其结构、分类、行为和分布。" },
  { id: "bio.bot", parentId: "bio", name: "Botany", nameZh: "植物学", description: "Plants, including structure, growth, reproduction, metabolism, and classification." , descriptionZh: "植物，包括结构、生长、繁殖、代谢和分类。" },
  { id: "bio.micr", parentId: "bio", name: "Microbiology", nameZh: "微生物学", description: "Microorganisms, including bacteria, viruses, fungi, and archaea; microbial physiology and ecology." , descriptionZh: "微生物，包括细菌、病毒、真菌和古细菌；微生物生理学和生态学。" },
  { id: "bio.neuro", parentId: "bio", name: "Neuroscience", nameZh: "神经科学", description: "Nervous system structure and function, from molecules and cells to behavior and cognition." , descriptionZh: "神经系统结构和功能，从分子和细胞到行为和认知。" },
  { id: "bio.dev", parentId: "bio", name: "Developmental Biology", nameZh: "发育生物学", description: "Growth, differentiation, and morphogenesis of organisms from embryo to adult." , descriptionZh: "生物体从胚胎到成体的生长、分化和形态发生。" },
  { id: "bio.evo", parentId: "bio", name: "Evolutionary Biology", nameZh: "进化生物学", description: "Origins, change, and diversification of life; natural selection, adaptation, and phylogeny." , descriptionZh: "生命的起源、变化和多样化；自然选择、适应和系统发育。" },
  { id: "bio.imm", parentId: "bio", name: "Immunobiology", nameZh: "免疫生物学", description: "Immune systems, host defense, and the cellular and molecular basis of immunity." , descriptionZh: "免疫系统、宿主防御以及免疫的细胞和分子基础。" },

  // Business & Management (quantitative finance is covered by q-fin).
  { id: "bus", parentId: null, name: "Business and Management", nameZh: "商业与管理", description: "All areas of business, management, and organization studies beyond quantitative finance." , descriptionZh: "除定量金融之外的所有商业、管理和组织研究领域。" },
  { id: "bus.gen", parentId: "bus", name: "General Management", nameZh: "综合管理", description: "Strategy, leadership, organization theory, and the general practice of management." , descriptionZh: "战略、领导力、组织理论和管理的一般实践。" },
  { id: "bus.mkt", parentId: "bus", name: "Marketing", nameZh: "营销", description: "Consumer behavior, branding, advertising, and the science of markets and exchange." , descriptionZh: "消费者行为、品牌、广告以及市场和交换科学。" },
  { id: "bus.acc", parentId: "bus", name: "Accounting", nameZh: "会计", description: "Financial and managerial accounting, auditing, and reporting." , descriptionZh: "财务和管理会计、审计和报告。" },
  { id: "bus.ops", parentId: "bus", name: "Operations and Supply Chain", nameZh: "运营和供应链", description: "Production, logistics, supply-chain management, and service operations." , descriptionZh: "生产、物流、供应链管理和服务运营。" },
  { id: "bus.hrm", parentId: "bus", name: "Human Resource Management", nameZh: "人力资源管理", description: "People management, talent, organizational behavior, and the employment relationship." , descriptionZh: "人员管理、人才、组织行为和雇佣关系。" },
  { id: "bus.str", parentId: "bus", name: "Strategy and Entrepreneurship", nameZh: "战略与创业", description: "Competitive strategy, innovation, new ventures, and entrepreneurial practice." , descriptionZh: "竞争战略、创新、新企业和创业实践。" },
  { id: "bus.is", parentId: "bus", name: "Information Systems", nameZh: "信息系统", description: "The design, use, and impact of information technology in organizations (cf. cs for the technical core)." , descriptionZh: "信息技术在组织中的设计、使用和影响（参见 cs 的技术核心）。" },

  // Agricultural Sciences.
  { id: "agri", parentId: null, name: "Agricultural Sciences", nameZh: "农业科学", description: "All areas of agriculture, crop and animal production, and the science of food systems." , descriptionZh: "农业、作物和动物生产以及粮食系统科学的所有领域。" },
  { id: "agri.crop", parentId: "agri", name: "Crop Science", nameZh: "作物科学", description: "Cultivation, breeding, and physiology of crop plants; agronomy and yield." , descriptionZh: "农作物的栽培、育种和生理学；农艺和产量。" },
  { id: "agri.soil", parentId: "agri", name: "Soil Science", nameZh: "土壤科学", description: "Soil formation, classification, fertility, and management." , descriptionZh: "土壤形成、分类、肥力和管理。" },
  { id: "agri.ani", parentId: "agri", name: "Animal Science", nameZh: "动物科学", description: "Breeding, nutrition, and management of livestock and poultry." , descriptionZh: "畜禽饲养、营养和管理。" },
  { id: "agri.hort", parentId: "agri", name: "Horticulture", nameZh: "园艺", description: "Cultivation of fruits, vegetables, flowers, and ornamental plants." , descriptionZh: "水果、蔬菜、花卉和观赏植物的种植。" },
  { id: "agri.ent", parentId: "agri", name: "Entomology", nameZh: "昆虫学", description: "Insects and their relationships to plants, animals, and humans; pest management." , descriptionZh: "昆虫及其与植物、动物和人类的关系；害虫管理。" },
  { id: "agri.food", parentId: "agri", name: "Food Science", nameZh: "食品科学", description: "Food chemistry, safety, processing, nutrition, and technology." , descriptionZh: "食品化学、安全、加工、营养和技术。" },

  // Sport & Exercise Science.
  { id: "sport", parentId: null, name: "Sport and Exercise Science", nameZh: "运动与运动科学", description: "All areas of sport, exercise, and kinesiology." , descriptionZh: "运动、锻炼和运动机能学的所有领域。" },
  { id: "sport.phys", parentId: "sport", name: "Exercise Physiology", nameZh: "运动生理学", description: "Physiological responses and adaptations to physical activity and training." , descriptionZh: "对身体活动和训练的生理反应和适应。" },
  { id: "sport.med", parentId: "sport", name: "Sports Medicine", nameZh: "运动医学", description: "Injury, prevention, rehabilitation, and the health of active populations." , descriptionZh: "伤害、预防、康复和活动人群的健康。" },
  { id: "sport.psy", parentId: "sport", name: "Sport Psychology", nameZh: "运动心理学", description: "Psychological and behavioral aspects of sport and physical activity." , descriptionZh: "体育和身体活动的心理和行为方面。" },
  { id: "sport.mgmt", parentId: "sport", name: "Sport Management", nameZh: "体育管理", description: "Governance, marketing, and management of sport organizations and events." , descriptionZh: "体育组织和赛事的治理、营销和管理。" },

  // Multidisciplinary / General catch-all.
  { id: "interdisc", parentId: null, name: "Multidisciplinary and General", nameZh: "多学科和一般", description: "Work that spans multiple disciplines or does not fit a single field." , descriptionZh: "跨越多个学科或不适合单一领域的工作。" },
  { id: "interdisc.gen", parentId: "interdisc", name: "General Science", nameZh: "普通科学", description: "Broad or introductory research of general interest across the sciences and scholarship." , descriptionZh: "整个科学和学术界普遍感兴趣的广泛或介绍性研究。" },
  { id: "interdisc.data", parentId: "interdisc", name: "Data Science", nameZh: "数据科学", description: "Methods and applications of data-driven discovery across domains (cf. cs.LG, stat.ML)." , descriptionZh: "跨领域数据驱动发现的方法和应用（参见 cs.LG、stat.ML）。" },
  { id: "interdisc.sustain", parentId: "interdisc", name: "Sustainability Science", nameZh: "可持续发展科学", description: "Interdisciplinary study of social-ecological systems, development, and planetary stewardship." , descriptionZh: "社会生态系统、发展和行星管理的跨学科研究。" },
];





// Seed the RBAC foundation: system roles, the permission catalog, and the
// default role → permission links. Idempotent via onConflictDoNothing.
async function seedRbac() {
  console.log("Seeding RBAC roles & permissions…");

  const roleDefs = [
    { key: "admin", name: "管理员", description: "拥有全部权限", isSystem: true },
    { key: "moderator", name: "审核员", description: "内容审核与工单处置", isSystem: true },
    { key: "author", name: "作者", description: "提交并管理自己的论文", isSystem: true },
    { key: "reader", name: "读者", description: "浏览与评论", isSystem: true },
  ];
  for (const r of roleDefs) {
    await db.insert(roles).values(r).onConflictDoNothing({ target: roles.key });
  }

  for (const p of PERMISSIONS) {
    await db
      .insert(permissions)
      .values({ key: p.key, name: p.name, group: p.group, description: p.description })
      .onConflictDoNothing({ target: permissions.key });
  }

  // Resolve ids for linking.
  const roleRows = await db.select({ id: roles.id, key: roles.key }).from(roles);
  const permRows = await db.select({ id: permissions.id, key: permissions.key }).from(permissions);
  const roleIdByKey = new Map(roleRows.map((r) => [r.key, r.id]));
  const permIdByKey = new Map(permRows.map((p) => [p.key, p.id]));

  const links: { roleId: number; permissionId: number }[] = [];
  for (const [roleKey, permKeys] of Object.entries(DEFAULT_ROLE_PERMISSIONS)) {
    const roleId = roleIdByKey.get(roleKey);
    if (roleId == null) continue;
    for (const pk of permKeys) {
      const permId = permIdByKey.get(pk);
      if (permId != null) links.push({ roleId, permissionId: permId });
    }
  }
  for (const l of links) {
    await db.insert(rolePermissions).values(l).onConflictDoNothing();
  }
}

async function main() {
  console.log("Seeding categories…");
  for (const c of CATEGORIES) {
    await db
      .insert(categories)
      .values(c)
      .onConflictDoUpdate({
        target: categories.id,
        set: {
          name: c.name,
          parentId: c.parentId,
          description: c.description,
          nameZh: c.nameZh,
          descriptionZh: c.descriptionZh,
        },
      });
  }

  await seedRbac();

  console.log("Seeding demo user…");
  const pw = await hashPassword("password123");
  const [user] = await db
    .insert(users)
    .values({ username: "demo", email: "demo@papex.dev", displayName: "Demo Author", passwordHash: pw })
    .onConflictDoNothing()
    .returning();

  console.log("Seeding admin user…");
  const adminPw = await hashPassword("admin123456");
  await db
    .insert(users)
    .values({
      username: "admin",
      email: "admin@papex.dev",
      displayName: "Administrator",
      passwordHash: adminPw,
      role: "admin",
    })
    .onConflictDoNothing();

  console.log("Seeding affiliation & author…");
  const [aff] = await db
    .insert(affiliations)
    .values({ name: "Papex University", country: "CN" })
    .onConflictDoNothing()
    .returning();
  await db
    .insert(authors)
    .values({ name: "Demo Author", affiliationId: aff?.id, userId: user?.id })
    .onConflictDoNothing();

  // NOTE: no demo papers are seeded here. Every paper in the catalogue MUST
  // carry a PDF (enforced by a CHECK constraint on paper_versions.pdf_url and
  // by the submission/import services). Demo/sample papers are populated with
  // real arXiv papers via `npm run db:seed-arxiv` instead.

  console.log("Seed complete.");
  process.exit(0);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
