// ---------------------------------------------------------------------------
// Code-first OpenAPI generator.
//
// Each API route documents itself in a sibling `route.openapi.ts` (the single
// source of truth for that endpoint). This script scans every fragment, merges
// them into the static base (info / components / security), and writes the
// machine-readable document consumed by /api/openapi.json.
//
// Run via: npm run openapi:generate  (also wired into predev / prebuild).
// ---------------------------------------------------------------------------
import { readdirSync, statSync, writeFileSync, existsSync } from "node:fs";
import { join, relative, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { baseSpec } from "./base";

const __dirname = dirname(fileURLToPath(import.meta.url));
const API_ROOT = join(__dirname, "..", "..", "app", "api");
const OUT_FILE = join(__dirname, "spec.generated.ts");

interface Fragment {
  path: string;
  item: Record<string, unknown>;
  file: string;
}

function collectFragments(dir: string, acc: string[]): void {
  if (!existsSync(dir)) return;
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const st = statSync(full);
    if (st.isDirectory()) {
      collectFragments(full, acc);
    } else if (entry === "route.openapi.ts") {
      acc.push(full);
    }
  }
}

const fragmentFiles: string[] = [];
collectFragments(API_ROOT, fragmentFiles);

const fragments: Fragment[] = [];
const errors: string[] = [];

for (const file of fragmentFiles) {
  const mod = await import(`file://${file}`);
  const fragment = mod.default as Record<string, unknown>;
  const keys = Object.keys(fragment);
  if (keys.length !== 1) {
    errors.push(
      `${relative(process.cwd(), file)} must export exactly one path object (found ${keys.length}: ${keys.join(", ")}).`,
    );
    continue;
  }
  const path = keys[0];
  if (!path.startsWith("/api/")) {
    errors.push(`${relative(process.cwd(), file)} path "${path}" must start with /api/.`);
    continue;
  }
  fragments.push({ path, item: fragment[path] as Record<string, unknown>, file });
}

if (errors.length) {
  console.error("OpenAPI generation failed:");
  for (const e of errors) console.error("  - " + e);
  process.exit(1);
}

// Stable order: by path, then merge methods.
fragments.sort((a, b) => a.path.localeCompare(b.path));

const paths: Record<string, unknown> = {};
for (const f of fragments) {
  if (paths[f.path]) {
    // Merge multiple fragments for the same path (defensive; normally 1 file per path).
    Object.assign(paths[f.path] as object, f.item);
  } else {
    paths[f.path] = f.item;
  }
}

const document = {
  ...baseSpec,
  paths,
};

const banner =
  "// AUTO-GENERATED by src/lib/openapi/generate.ts. DO NOT EDIT BY HAND.\n" +
  "// To change the API docs, edit the per-route `route.openapi.ts` fragments\n" +
  "// (or `base.ts` for shared components) and run `npm run openapi:generate`.\n" +
  "// Source routes: " + fragments.length + " path fragments.\n\n";

const serialized = JSON.stringify(document, null, 2)
  // Compact the *inside* of deeply nested schema objects? Keep readable.
  .replace(/\"(application\/json|application\/pdf)\":/g, '"$1":');

const out =
  banner +
  "export const openapiSpec = " +
  serialized +
  " as const;\n";

writeFileSync(OUT_FILE, out, "utf8");

const opCount = fragments.reduce(
  (n, f) => n + Object.keys(f.item).length,
  0,
);
console.log(
  `✓ Generated ${relative(process.cwd(), OUT_FILE)} — ` +
    `${fragments.length} paths, ${opCount} operations.`,
);
